-- Generated by cargo-yauth
-- Registered user accounts.
CREATE TABLE IF NOT EXISTS `yauth_users` (
    `id` CHAR(36) PRIMARY KEY,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `display_name` VARCHAR(255),
    `email_verified` TINYINT(1) NOT NULL DEFAULT false,
    `role` VARCHAR(255) NOT NULL DEFAULT 'user',
    `banned` TINYINT(1) NOT NULL DEFAULT false,
    `banned_reason` VARCHAR(255),
    `banned_until` DATETIME,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Ephemeral challenge storage for CSRF, WebAuthn, and MFA flows.
CREATE TABLE IF NOT EXISTS `yauth_challenges` (
    `key` VARCHAR(255) PRIMARY KEY,
    `value` JSON NOT NULL,
    `expires_at` DATETIME NOT NULL
) ENGINE=InnoDB;

-- Per-operation rate limit counters.
CREATE TABLE IF NOT EXISTS `yauth_rate_limits` (
    `key` VARCHAR(255) PRIMARY KEY,
    `count` INT NOT NULL DEFAULT 1,
    `window_start` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Revoked JWT token IDs (JTI). TTL-based expiration.
CREATE TABLE IF NOT EXISTS `yauth_revocations` (
    `key` VARCHAR(255) PRIMARY KEY,
    `expires_at` DATETIME NOT NULL
) ENGINE=InnoDB;

-- OAuth CSRF state tokens. Consumed on callback.
CREATE TABLE IF NOT EXISTS `yauth_oauth_states` (
    `state` VARCHAR(255) PRIMARY KEY,
    `provider` VARCHAR(255) NOT NULL,
    `redirect_url` VARCHAR(255),
    `expires_at` DATETIME NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Passwordless login tokens. Single-use, time-limited.
CREATE TABLE IF NOT EXISTS `yauth_magic_links` (
    `id` CHAR(36) PRIMARY KEY,
    `email` VARCHAR(255) NOT NULL,
    `token_hash` VARCHAR(255) NOT NULL UNIQUE,
    `expires_at` DATETIME NOT NULL,
    `used` TINYINT(1) NOT NULL DEFAULT false,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Registered OAuth2 server clients.
CREATE TABLE IF NOT EXISTS `yauth_oauth2_clients` (
    `id` CHAR(36) PRIMARY KEY,
    `client_id` VARCHAR(255) NOT NULL UNIQUE,
    `client_secret_hash` VARCHAR(255),
    `redirect_uris` JSON NOT NULL,
    `client_name` VARCHAR(255),
    `grant_types` JSON NOT NULL,
    `scopes` JSON,
    `is_public` TINYINT(1) NOT NULL DEFAULT false,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Webhook endpoint configurations.
CREATE TABLE IF NOT EXISTS `yauth_webhooks` (
    `id` CHAR(36) PRIMARY KEY,
    `url` VARCHAR(255) NOT NULL,
    `secret` VARCHAR(255) NOT NULL,
    `events` JSON NOT NULL,
    `active` TINYINT(1) NOT NULL DEFAULT true,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- OIDC nonce values for replay protection.
CREATE TABLE IF NOT EXISTS `yauth_oidc_nonces` (
    `id` CHAR(36) PRIMARY KEY,
    `nonce_hash` VARCHAR(255) NOT NULL UNIQUE,
    `authorization_code_id` CHAR(36) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Active user sessions. One row per login.
CREATE TABLE IF NOT EXISTS `yauth_sessions` (
    `id` CHAR(36) PRIMARY KEY,
    `user_id` CHAR(36) NOT NULL,
    `token_hash` VARCHAR(64) NOT NULL UNIQUE,
    `ip_address` VARCHAR(255),
    `user_agent` VARCHAR(255),
    `expires_at` DATETIME NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `yauth_users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Append-only authentication event log.
CREATE TABLE IF NOT EXISTS `yauth_audit_log` (
    `id` CHAR(36) PRIMARY KEY,
    `user_id` CHAR(36),
    `event_type` VARCHAR(255) NOT NULL,
    `metadata` JSON,
    `ip_address` VARCHAR(255),
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `yauth_users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Hashed passwords. One row per user.
CREATE TABLE IF NOT EXISTS `yauth_passwords` (
    `user_id` CHAR(36) PRIMARY KEY,
    `password_hash` VARCHAR(255) NOT NULL,
    FOREIGN KEY (`user_id`) REFERENCES `yauth_users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Pending email verification tokens.
CREATE TABLE IF NOT EXISTS `yauth_email_verifications` (
    `id` CHAR(36) PRIMARY KEY,
    `user_id` CHAR(36),
    `token_hash` VARCHAR(64) NOT NULL UNIQUE,
    `expires_at` DATETIME NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `yauth_users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Pending password reset tokens.
CREATE TABLE IF NOT EXISTS `yauth_password_resets` (
    `id` CHAR(36) PRIMARY KEY,
    `user_id` CHAR(36),
    `token_hash` VARCHAR(64) NOT NULL UNIQUE,
    `expires_at` DATETIME NOT NULL,
    `used_at` DATETIME,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `yauth_users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- WebAuthn/passkey credentials. Multiple per user.
CREATE TABLE IF NOT EXISTS `yauth_webauthn_credentials` (
    `id` CHAR(36) PRIMARY KEY,
    `user_id` CHAR(36),
    `name` VARCHAR(255) NOT NULL,
    `aaguid` VARCHAR(255),
    `device_name` VARCHAR(255),
    `credential` JSON NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `last_used_at` DATETIME,
    FOREIGN KEY (`user_id`) REFERENCES `yauth_users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- TOTP secrets for MFA. One per user.
CREATE TABLE IF NOT EXISTS `yauth_totp_secrets` (
    `id` CHAR(36) PRIMARY KEY,
    `user_id` CHAR(36) UNIQUE,
    `encrypted_secret` VARCHAR(255) NOT NULL,
    `verified` TINYINT(1) NOT NULL DEFAULT false,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `yauth_users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- MFA backup codes. Multiple per user, single-use.
CREATE TABLE IF NOT EXISTS `yauth_backup_codes` (
    `id` CHAR(36) PRIMARY KEY,
    `user_id` CHAR(36),
    `code_hash` VARCHAR(64) NOT NULL,
    `used` TINYINT(1) NOT NULL DEFAULT false,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `yauth_users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Linked OAuth provider accounts.
CREATE TABLE IF NOT EXISTS `yauth_oauth_accounts` (
    `id` CHAR(36) PRIMARY KEY,
    `user_id` CHAR(36),
    `provider` VARCHAR(255) NOT NULL,
    `provider_user_id` VARCHAR(255) NOT NULL,
    `access_token_enc` VARCHAR(255),
    `refresh_token_enc` VARCHAR(255),
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `expires_at` DATETIME,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `yauth_users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- JWT refresh tokens with rotation family tracking.
CREATE TABLE IF NOT EXISTS `yauth_refresh_tokens` (
    `id` CHAR(36) PRIMARY KEY,
    `user_id` CHAR(36),
    `token_hash` VARCHAR(64) NOT NULL UNIQUE,
    `family_id` CHAR(36) NOT NULL,
    `expires_at` DATETIME NOT NULL,
    `revoked` TINYINT(1) NOT NULL DEFAULT false,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `yauth_users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- API keys. Identified by prefix, verified by hash.
CREATE TABLE IF NOT EXISTS `yauth_api_keys` (
    `id` CHAR(36) PRIMARY KEY,
    `user_id` CHAR(36),
    `key_prefix` VARCHAR(12) NOT NULL UNIQUE,
    `key_hash` VARCHAR(64) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `scopes` JSON,
    `last_used_at` DATETIME,
    `expires_at` DATETIME,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `yauth_users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- OAuth2 authorization codes. Single-use, time-limited.
CREATE TABLE IF NOT EXISTS `yauth_authorization_codes` (
    `id` CHAR(36) PRIMARY KEY,
    `code_hash` VARCHAR(255) NOT NULL UNIQUE,
    `client_id` VARCHAR(255) NOT NULL,
    `user_id` CHAR(36),
    `scopes` JSON,
    `redirect_uri` VARCHAR(255) NOT NULL,
    `code_challenge` VARCHAR(255) NOT NULL,
    `code_challenge_method` VARCHAR(255) NOT NULL,
    `expires_at` DATETIME NOT NULL,
    `used` TINYINT(1) NOT NULL DEFAULT false,
    `nonce` VARCHAR(255),
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `yauth_users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- User consent records for OAuth2 clients.
CREATE TABLE IF NOT EXISTS `yauth_consents` (
    `id` CHAR(36) PRIMARY KEY,
    `user_id` CHAR(36),
    `client_id` VARCHAR(255) NOT NULL,
    `scopes` JSON,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `yauth_users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Device authorization flow codes.
CREATE TABLE IF NOT EXISTS `yauth_device_codes` (
    `id` CHAR(36) PRIMARY KEY,
    `device_code_hash` VARCHAR(255) NOT NULL UNIQUE,
    `user_code` VARCHAR(255) NOT NULL UNIQUE,
    `client_id` VARCHAR(255) NOT NULL,
    `scopes` JSON,
    `user_id` CHAR(36),
    `status` VARCHAR(255) NOT NULL DEFAULT 'pending',
    `interval` INT NOT NULL DEFAULT 5,
    `expires_at` DATETIME NOT NULL,
    `last_polled_at` DATETIME,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `yauth_users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Account lockout state. One row per user.
CREATE TABLE IF NOT EXISTS `yauth_account_locks` (
    `id` CHAR(36) PRIMARY KEY,
    `user_id` CHAR(36) UNIQUE,
    `failed_count` INT NOT NULL DEFAULT 0,
    `locked_until` DATETIME,
    `lock_count` INT NOT NULL DEFAULT 0,
    `locked_reason` VARCHAR(255),
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `yauth_users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Account unlock tokens. Time-limited.
CREATE TABLE IF NOT EXISTS `yauth_unlock_tokens` (
    `id` CHAR(36) PRIMARY KEY,
    `user_id` CHAR(36),
    `token_hash` VARCHAR(255) NOT NULL UNIQUE,
    `expires_at` DATETIME NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `yauth_users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Webhook delivery attempts and responses.
CREATE TABLE IF NOT EXISTS `yauth_webhook_deliveries` (
    `id` CHAR(36) PRIMARY KEY,
    `webhook_id` CHAR(36),
    `event_type` VARCHAR(255) NOT NULL,
    `payload` JSON NOT NULL,
    `status_code` SMALLINT,
    `response_body` TEXT,
    `success` TINYINT(1) NOT NULL DEFAULT false,
    `attempt` INT NOT NULL DEFAULT 1,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`webhook_id`) REFERENCES `yauth_webhooks`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

