package main

import (
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

func newGenSecretsCmd() *cobra.Command {
	var (
		out   string
		force bool
	)
	cmd := &cobra.Command{
		Use:          "gen-secrets",
		Short:        "Generate random secrets and write a .env file",
		SilenceUsage: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			if !force {
				if _, err := os.Stat(out); err == nil {
					return fmt.Errorf("%s already exists; pass --force to overwrite", out)
				}
			}
			jwt, err := randomHex(32) // 64 hex chars = 256 bits
			if err != nil {
				return err
			}
			mfaKey, err := randomBase64(32)
			if err != nil {
				return err
			}
			webhookSecret, err := randomHex(32)
			if err != nil {
				return err
			}
			lines := []string{
				"# Generated by yauth gen-secrets — do not commit",
				"JWT_SECRET=" + jwt,
				"MFA_ENCRYPTION_KEY=" + mfaKey,
				"WEBHOOK_DEFAULT_SECRET=" + webhookSecret,
			}
			if err := os.WriteFile(out, []byte(strings.Join(lines, "\n")+"\n"), 0o600); err != nil {
				return fmt.Errorf("write %s: %w", out, err)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "wrote %s (3 secrets)\n", out)
			return nil
		},
	}
	cmd.Flags().StringVarP(&out, "out", "o", ".env", "path to write")
	cmd.Flags().BoolVar(&force, "force", false, "overwrite if file exists")
	return cmd
}

func randomHex(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

func randomBase64(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return base64.StdEncoding.EncodeToString(b), nil
}
