-- Generated by toasty-dev from yauth-toasty models
-- DO NOT EDIT — regenerate with: cargo run --bin toasty-dev --features sqlite,dev-cli -- generate

CREATE TABLE "yauth_webauthn_credentials" (
    "id" BLOB NOT NULL,
    "user_id" BLOB NOT NULL,
    "name" TEXT NOT NULL,
    "aaguid" TEXT,
    "device_name" TEXT,
    "credential" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    "last_used_at" TEXT,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_webauthn_credentials_by_id" ON "yauth_webauthn_credentials" ("id");
-- #[toasty::breakpoint]
CREATE INDEX "index_yauth_webauthn_credentials_by_user_id" ON "yauth_webauthn_credentials" ("user_id");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_device_codes" (
    "id" BLOB NOT NULL,
    "device_code_hash" TEXT NOT NULL,
    "user_code" TEXT NOT NULL,
    "client_id" TEXT NOT NULL,
    "scopes" TEXT,
    "user_id" BLOB,
    "status" TEXT NOT NULL,
    "interval" INTEGER NOT NULL,
    "expires_at" TEXT NOT NULL,
    "last_polled_at" TEXT,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_device_codes_by_id" ON "yauth_device_codes" ("id");
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_device_codes_by_device_code_hash" ON "yauth_device_codes" ("device_code_hash");
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_device_codes_by_user_code" ON "yauth_device_codes" ("user_code");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_webhook_deliveries" (
    "id" BLOB NOT NULL,
    "webhook_id" BLOB NOT NULL,
    "event_type" TEXT NOT NULL,
    "payload" TEXT NOT NULL,
    "status_code" INTEGER,
    "response_body" TEXT,
    "success" BOOLEAN NOT NULL,
    "attempt" INTEGER NOT NULL,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_webhook_deliveries_by_id" ON "yauth_webhook_deliveries" ("id");
-- #[toasty::breakpoint]
CREATE INDEX "index_yauth_webhook_deliveries_by_webhook_id" ON "yauth_webhook_deliveries" ("webhook_id");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_oauth_accounts" (
    "id" BLOB NOT NULL,
    "user_id" BLOB NOT NULL,
    "provider" TEXT NOT NULL,
    "provider_user_id" TEXT NOT NULL,
    "access_token_enc" TEXT,
    "refresh_token_enc" TEXT,
    "created_at" TEXT NOT NULL,
    "expires_at" TEXT,
    "updated_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_oauth_accounts_by_id" ON "yauth_oauth_accounts" ("id");
-- #[toasty::breakpoint]
CREATE INDEX "index_yauth_oauth_accounts_by_user_id" ON "yauth_oauth_accounts" ("user_id");
-- #[toasty::breakpoint]
CREATE INDEX "index_yauth_oauth_accounts_by_provider" ON "yauth_oauth_accounts" ("provider");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_refresh_tokens" (
    "id" BLOB NOT NULL,
    "user_id" BLOB NOT NULL,
    "token_hash" TEXT NOT NULL,
    "family_id" BLOB NOT NULL,
    "expires_at" TEXT NOT NULL,
    "revoked" BOOLEAN NOT NULL,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_refresh_tokens_by_id" ON "yauth_refresh_tokens" ("id");
-- #[toasty::breakpoint]
CREATE INDEX "index_yauth_refresh_tokens_by_user_id" ON "yauth_refresh_tokens" ("user_id");
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_refresh_tokens_by_token_hash" ON "yauth_refresh_tokens" ("token_hash");
-- #[toasty::breakpoint]
CREATE INDEX "index_yauth_refresh_tokens_by_family_id" ON "yauth_refresh_tokens" ("family_id");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_password_resets" (
    "id" BLOB NOT NULL,
    "user_id" BLOB NOT NULL,
    "token_hash" TEXT NOT NULL,
    "expires_at" TEXT NOT NULL,
    "used_at" TEXT,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_password_resets_by_id" ON "yauth_password_resets" ("id");
-- #[toasty::breakpoint]
CREATE INDEX "index_yauth_password_resets_by_user_id" ON "yauth_password_resets" ("user_id");
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_password_resets_by_token_hash" ON "yauth_password_resets" ("token_hash");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_api_keys" (
    "id" BLOB NOT NULL,
    "user_id" BLOB NOT NULL,
    "key_prefix" TEXT NOT NULL,
    "key_hash" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "scopes" TEXT,
    "last_used_at" TEXT,
    "expires_at" TEXT,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_api_keys_by_id" ON "yauth_api_keys" ("id");
-- #[toasty::breakpoint]
CREATE INDEX "index_yauth_api_keys_by_user_id" ON "yauth_api_keys" ("user_id");
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_api_keys_by_key_prefix" ON "yauth_api_keys" ("key_prefix");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_unlock_tokens" (
    "id" BLOB NOT NULL,
    "user_id" BLOB NOT NULL,
    "token_hash" TEXT NOT NULL,
    "expires_at" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_unlock_tokens_by_id" ON "yauth_unlock_tokens" ("id");
-- #[toasty::breakpoint]
CREATE INDEX "index_yauth_unlock_tokens_by_user_id" ON "yauth_unlock_tokens" ("user_id");
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_unlock_tokens_by_token_hash" ON "yauth_unlock_tokens" ("token_hash");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_authorization_codes" (
    "id" BLOB NOT NULL,
    "code_hash" TEXT NOT NULL,
    "client_id" TEXT NOT NULL,
    "user_id" BLOB NOT NULL,
    "scopes" TEXT,
    "redirect_uri" TEXT NOT NULL,
    "code_challenge" TEXT NOT NULL,
    "code_challenge_method" TEXT NOT NULL,
    "expires_at" TEXT NOT NULL,
    "used" BOOLEAN NOT NULL,
    "nonce" TEXT,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_authorization_codes_by_id" ON "yauth_authorization_codes" ("id");
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_authorization_codes_by_code_hash" ON "yauth_authorization_codes" ("code_hash");
-- #[toasty::breakpoint]
CREATE INDEX "index_yauth_authorization_codes_by_user_id" ON "yauth_authorization_codes" ("user_id");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_audit_log" (
    "id" BLOB NOT NULL,
    "user_id" BLOB,
    "event_type" TEXT NOT NULL,
    "metadata" TEXT,
    "ip_address" TEXT,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_audit_log_by_id" ON "yauth_audit_log" ("id");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_sessions" (
    "id" BLOB NOT NULL,
    "user_id" BLOB NOT NULL,
    "token_hash" TEXT NOT NULL,
    "ip_address" TEXT,
    "user_agent" TEXT,
    "expires_at" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_sessions_by_id" ON "yauth_sessions" ("id");
-- #[toasty::breakpoint]
CREATE INDEX "index_yauth_sessions_by_user_id" ON "yauth_sessions" ("user_id");
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_sessions_by_token_hash" ON "yauth_sessions" ("token_hash");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_magic_links" (
    "id" BLOB NOT NULL,
    "email" TEXT NOT NULL,
    "token_hash" TEXT NOT NULL,
    "expires_at" TEXT NOT NULL,
    "used" BOOLEAN NOT NULL,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_magic_links_by_id" ON "yauth_magic_links" ("id");
-- #[toasty::breakpoint]
CREATE INDEX "index_yauth_magic_links_by_email" ON "yauth_magic_links" ("email");
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_magic_links_by_token_hash" ON "yauth_magic_links" ("token_hash");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_oauth2_clients" (
    "id" BLOB NOT NULL,
    "client_id" TEXT NOT NULL,
    "client_secret_hash" TEXT,
    "redirect_uris" TEXT NOT NULL,
    "client_name" TEXT,
    "grant_types" TEXT NOT NULL,
    "scopes" TEXT,
    "is_public" BOOLEAN NOT NULL,
    "created_at" TEXT NOT NULL,
    "token_endpoint_auth_method" TEXT,
    "public_key_pem" TEXT,
    "jwks_uri" TEXT,
    "banned_at" TEXT,
    "banned_reason" TEXT,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_oauth2_clients_by_id" ON "yauth_oauth2_clients" ("id");
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_oauth2_clients_by_client_id" ON "yauth_oauth2_clients" ("client_id");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_passwords" (
    "user_id" BLOB NOT NULL,
    "password_hash" TEXT NOT NULL,
    PRIMARY KEY ("user_id")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_passwords_by_user_id" ON "yauth_passwords" ("user_id");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_backup_codes" (
    "id" BLOB NOT NULL,
    "user_id" BLOB NOT NULL,
    "code_hash" TEXT NOT NULL,
    "used" BOOLEAN NOT NULL,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_backup_codes_by_id" ON "yauth_backup_codes" ("id");
-- #[toasty::breakpoint]
CREATE INDEX "index_yauth_backup_codes_by_user_id" ON "yauth_backup_codes" ("user_id");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_consents" (
    "id" BLOB NOT NULL,
    "user_id" BLOB NOT NULL,
    "client_id" TEXT NOT NULL,
    "scopes" TEXT,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_consents_by_id" ON "yauth_consents" ("id");
-- #[toasty::breakpoint]
CREATE INDEX "index_yauth_consents_by_user_id" ON "yauth_consents" ("user_id");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_rate_limits" (
    "key" TEXT NOT NULL,
    "count" INTEGER NOT NULL,
    "window_start" TEXT NOT NULL,
    PRIMARY KEY ("key")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_rate_limits_by_key" ON "yauth_rate_limits" ("key");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_users" (
    "id" BLOB NOT NULL,
    "email" TEXT NOT NULL,
    "display_name" TEXT,
    "email_verified" BOOLEAN NOT NULL,
    "role" TEXT NOT NULL,
    "banned" BOOLEAN NOT NULL,
    "banned_reason" TEXT,
    "banned_until" TEXT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_users_by_id" ON "yauth_users" ("id");
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_users_by_email" ON "yauth_users" ("email");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_revocations" (
    "key" TEXT NOT NULL,
    "expires_at" TEXT NOT NULL,
    PRIMARY KEY ("key")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_revocations_by_key" ON "yauth_revocations" ("key");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_oauth_states" (
    "state" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "redirect_url" TEXT,
    "expires_at" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("state")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_oauth_states_by_state" ON "yauth_oauth_states" ("state");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_webhooks" (
    "id" BLOB NOT NULL,
    "url" TEXT NOT NULL,
    "secret" TEXT NOT NULL,
    "events" TEXT NOT NULL,
    "active" BOOLEAN NOT NULL,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_webhooks_by_id" ON "yauth_webhooks" ("id");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_challenges" (
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "expires_at" TEXT NOT NULL,
    PRIMARY KEY ("key")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_challenges_by_key" ON "yauth_challenges" ("key");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_account_locks" (
    "id" BLOB NOT NULL,
    "user_id" BLOB NOT NULL,
    "failed_count" INTEGER NOT NULL,
    "locked_until" TEXT,
    "lock_count" INTEGER NOT NULL,
    "locked_reason" TEXT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_account_locks_by_id" ON "yauth_account_locks" ("id");
-- #[toasty::breakpoint]
CREATE INDEX "index_yauth_account_locks_by_user_id" ON "yauth_account_locks" ("user_id");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_totp_secrets" (
    "id" BLOB NOT NULL,
    "user_id" BLOB NOT NULL,
    "encrypted_secret" TEXT NOT NULL,
    "verified" BOOLEAN NOT NULL,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_totp_secrets_by_id" ON "yauth_totp_secrets" ("id");
-- #[toasty::breakpoint]
CREATE INDEX "index_yauth_totp_secrets_by_user_id" ON "yauth_totp_secrets" ("user_id");
-- #[toasty::breakpoint]
CREATE TABLE "yauth_email_verifications" (
    "id" BLOB NOT NULL,
    "user_id" BLOB NOT NULL,
    "token_hash" TEXT NOT NULL,
    "expires_at" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    PRIMARY KEY ("id")
);
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_email_verifications_by_id" ON "yauth_email_verifications" ("id");
-- #[toasty::breakpoint]
CREATE INDEX "index_yauth_email_verifications_by_user_id" ON "yauth_email_verifications" ("user_id");
-- #[toasty::breakpoint]
CREATE UNIQUE INDEX "index_yauth_email_verifications_by_token_hash" ON "yauth_email_verifications" ("token_hash");