// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Session info returned by admin list endpoint.
 */
export type AdminSessionInfo = { id: string, user_id: string, ip_address: string | null, user_agent: string | null, expires_at: string, created_at: string, };
