// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiKeyResponse = {
	id: string;
	name: string;
	prefix: string;
	scopes: Array<string> | null;
	last_used_at: string | null;
	expires_at: string | null;
	created_at: string;
};
