// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Server-side auth configuration exposed to frontends via `GET /config`.
 */
export type AuthConfigResponse = { 
/**
 * Whether new user registration is allowed.
 */
allow_signups: boolean, 
/**
 * Whether newly registered users must verify their email before logging in.
 */
require_email_verification: boolean, };
