// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMethod } from "./AuthMethod";

export type AuthUser = {
	id: string;
	email: string;
	display_name: string | null;
	email_verified: boolean;
	role: string;
	banned: boolean;
	auth_method: AuthMethod;
	/**
	 * Scopes granted to this token (from JWT `scope` claim). None means unrestricted.
	 */
	scopes?: Array<string> | null;
};
