// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSessionInfo } from "./AdminSessionInfo";

/**
 * Response type for `GET /admin/sessions` (schema-only, used for OpenAPI spec).
 */
export type PaginatedSessionsResponse = { sessions: Array<AdminSessionInfo>, total: bigint, page: bigint, per_page: bigint, };
