// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PasskeyLoginFinishRequest = {
	challenge_id: string;
	credential: unknown;
};
