// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TokenRequest = {
	email: string;
	password: string;
	/**
	 * Optional space-separated OAuth2 scopes (e.g. "read:runs write:runs").
	 */
	scope: string | null;
};
