/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * yauth-go
 * OpenAPI 3.1 specification for the yauth-go authentication library. Routes are mounted by each plugin under whatever prefix the embedder chooses (commonly `/api/auth`).
 * OpenAPI spec version: 0.0.1
 */
import { customFetch } from './mutator';
export type AdminAuditEntryJSONMetadata = {[key: string]: unknown};

export interface AdminAuditEntryJSON {
  created_at: string;
  event_type: string;
  id: string;
  ip_address?: string;
  metadata?: AdminAuditEntryJSONMetadata;
  user_id?: string;
}

export interface AdminBanRequest {
  reason: string;
  until?: string;
}

export interface AdminDeleteSessionsResponse {
  deleted: number;
}

export interface AdminImpersonateResponse {
  banned: boolean;
  banned_reason?: string;
  banned_until?: string;
  created_at: string;
  display_name?: string;
  email: string;
  email_verified: boolean;
  id: string;
  role: string;
  updated_at: string;
}

export interface AdminListAuditResponse {
  /** @nullable */
  entries: AdminAuditEntryJSON[] | null;
}

export interface AdminSessionJSON {
  created_at: string;
  expires_at: string;
  id: string;
  ip_address?: string;
  user_agent?: string;
  user_id: string;
}

export interface AdminListSessionsResponse {
  page: number;
  per_page: number;
  /** @nullable */
  sessions: AdminSessionJSON[] | null;
  total: number;
}

export interface AdminUserJSON {
  banned: boolean;
  banned_reason?: string;
  banned_until?: string;
  created_at: string;
  display_name?: string;
  email: string;
  email_verified: boolean;
  id: string;
  role: string;
  updated_at: string;
}

export interface AdminListUsersResponse {
  page: number;
  per_page: number;
  total: number;
  /** @nullable */
  users: AdminUserJSON[] | null;
}

export interface AdminPatchUserRequest {
  display_name?: string;
  email_verified?: boolean;
  role?: string;
}

export interface ApiKeyCreateRequest {
  expires_in_days?: number;
  name: string;
  /** @nullable */
  scopes?: string[] | null;
}

export interface ApiKeyCreateResponse {
  created_at: string;
  expires_at?: string;
  id: string;
  key: string;
  name: string;
  prefix: string;
  /** @nullable */
  scopes: string[] | null;
}

export interface ApiKeyJSON {
  created_at: string;
  expires_at?: string;
  id: string;
  last_used_at?: string;
  name: string;
  prefix: string;
  /** @nullable */
  scopes: string[] | null;
}

export interface BearerRefreshRequest {
  refresh_token: string;
}

export interface BearerRevokeRequest {
  refresh_token: string;
}

export interface BearerTokenRequest {
  email: string;
  password: string;
  scope?: string;
}

export interface BearerTokenResponse {
  access_token: string;
  expires_in: number;
  refresh_token: string;
  token_type: string;
}

export interface ConfigResponse {
  allow_signups: boolean;
  require_email_verification: boolean;
}

export interface EmailForgotPasswordRequest {
  email: string;
}

export interface EmailForgotPasswordResponse {
  message: string;
}

export interface EmailPasswordChangePasswordRequest {
  current_password: string;
  new_password: string;
}

export interface EmailPasswordChangePasswordResponse {
  message: string;
}

export interface EmailPasswordLoginMfaResponse {
  pending_session_id: string;
  require_mfa: boolean;
}

export interface EmailPasswordLoginRequest {
  email: string;
  password: string;
  remember_me?: boolean;
}

export interface UserJSON {
  display_name?: string;
  email: string;
  email_verified: boolean;
  id: string;
  role: string;
}

export interface EmailPasswordLoginResponse {
  user: UserJSON;
}

export interface EmailPasswordPatchMeRequest {
  display_name?: string;
}

export interface EmailPasswordPatchMeResponse {
  auth_method: string;
  banned: boolean;
  display_name?: string;
  email: string;
  email_verified: boolean;
  id: string;
  role: string;
  /** @nullable */
  scopes: string[] | null;
}

export interface EmailPasswordRegisterRequest {
  display_name?: string;
  email: string;
  password: string;
}

export interface EmailPasswordRegisterResponse {
  message: string;
}

export interface EmailPasswordSessionResponse {
  auth_method: string;
  banned: boolean;
  display_name?: string;
  email: string;
  email_verified: boolean;
  id: string;
  role: string;
  /** @nullable */
  scopes: string[] | null;
}

export interface EmailResendVerificationRequest {
  email: string;
}

export interface EmailResendVerificationResponse {
  message: string;
}

export interface EmailResetPasswordRequest {
  password: string;
  token: string;
}

export interface EmailResetPasswordResponse {
  message: string;
}

export interface EmailVerifyRequest {
  token: string;
}

export interface EmailVerifyResponse {
  message: string;
}

export interface ErrorPayload {
  code: string;
  message: string;
}

export interface ErrorBody {
  error: ErrorPayload;
}

export interface JwksKey {
  alg: string;
  crv?: string;
  e?: string;
  kid: string;
  kty: string;
  n?: string;
  use?: string;
  x?: string;
  y?: string;
}

export interface JwksDocument {
  /** @nullable */
  keys: JwksKey[] | null;
}

export interface LockoutLockedAccountJSON {
  email: string;
  failed_count: number;
  lock_count: number;
  locked_reason?: string;
  locked_until?: string;
  user_id: string;
}

export interface LockoutStateResponse {
  /** @nullable */
  locked: LockoutLockedAccountJSON[] | null;
}

export interface LockoutUnlockReqRequest {
  email: string;
}

export interface LockoutUnlockReqResponse {
  message: string;
}

export interface LockoutUnlockRequest {
  token: string;
}

export interface LockoutUnlockResponse {
  message: string;
}

export interface MagicLinkSendRequest {
  email: string;
}

export interface MagicLinkSendResponse {
  message: string;
}

export interface MagicLinkVerifyRequest {
  token: string;
}

export interface MagicLinkVerifyResponse {
  display_name?: string;
  email: string;
  email_verified: boolean;
  user_id: string;
}

export interface MfaBackupCodesCountResponse {
  remaining: number;
}

export interface MfaConfirmRequest {
  code: string;
}

export interface MfaMessageResponse {
  message: string;
}

export interface MfaRegenerateResponse {
  /** @nullable */
  backup_codes: string[] | null;
}

export interface MfaSetupResponse {
  /** @nullable */
  backup_codes: string[] | null;
  otpauth_url: string;
  secret: string;
}

export interface MfaVerifyRequest {
  code: string;
  pending_session_id: string;
}

export interface MfaVerifyResponse {
  display_name?: string;
  email: string;
  email_verified: boolean;
  user_id: string;
}

export interface Oauth2AuthorizeRedirect {
  redirect_url: string;
}

export interface Oauth2ClientJSON {
  banned: boolean;
  banned_reason?: string;
  client_id: string;
  created_at: string;
  /** @nullable */
  grant_types: string[] | null;
  has_public_key: boolean;
  id: string;
  is_public: boolean;
  jwks_uri?: string;
  name?: string;
  /** @nullable */
  redirect_uris: string[] | null;
  /** @nullable */
  scopes: string[] | null;
  token_endpoint_auth_method?: string;
}

export interface Oauth2BannedClientsResponse {
  /** @nullable */
  banned: Oauth2ClientJSON[] | null;
}

export interface Oauth2ConsentClient {
  id: string;
  name?: string;
}

export interface Oauth2ConsentPayload {
  client: Oauth2ConsentClient;
  csrf_token: string;
  request_id: string;
  /** @nullable */
  scopes: string[] | null;
}

export interface Oauth2ConsentRequest {
  approved: boolean;
  csrf_token: string;
  request_id: string;
}

export interface Oauth2CreateClientRequest {
  /** @nullable */
  grant_types: string[] | null;
  is_public: boolean;
  jwks_uri?: string;
  name?: string;
  public_key_pem?: string;
  /** @nullable */
  redirect_uris: string[] | null;
  /** @nullable */
  scopes: string[] | null;
  token_endpoint_auth_method?: string;
}

export interface Oauth2CreateClientResponse {
  client: Oauth2ClientJSON;
  client_secret?: string;
}

export interface Oauth2DeviceAuthResponse {
  device_code: string;
  expires_in: number;
  interval: number;
  user_code: string;
  verification_uri: string;
}

export interface Oauth2DeviceVerifyRequest {
  user_code: string;
}

export interface Oauth2DeviceVerifyResponse {
  status: string;
}

export interface Oauth2IntrospectResponse {
  active: boolean;
  client_id?: string;
  exp?: number;
  iat?: number;
  iss?: string;
  scope?: string;
  sub?: string;
  token_type?: string;
}

export interface Oauth2PatchClientRequest {
  banned?: boolean;
  banned_reason?: string;
  public_key_pem?: string;
}

export interface Oauth2TokenResponse {
  access_token: string;
  expires_in: number;
  id_token?: string;
  refresh_token?: string;
  scope?: string;
  token_type: string;
}

export interface OauthAccountJSON {
  created_at: string;
  expires_at?: string;
  provider: string;
  provider_user_id: string;
}

export interface OauthCallbackBody {
  code: string;
  state: string;
}

export interface OauthCallbackResponse {
  display_name?: string;
  email: string;
  email_verified: boolean;
  user_id: string;
}

export interface OauthLinkResponse {
  auth_url: string;
}

export interface OidcDiscoveryDoc {
  authorization_endpoint?: string;
  /** @nullable */
  grant_types_supported: string[] | null;
  /** @nullable */
  id_token_signing_alg_values_supported: string[] | null;
  issuer: string;
  jwks_uri: string;
  /** @nullable */
  response_types_supported: string[] | null;
  /** @nullable */
  scopes_supported?: string[] | null;
  /** @nullable */
  subject_types_supported: string[] | null;
  token_endpoint?: string;
  userinfo_endpoint: string;
}

export interface OidcUserInfoResponse {
  email?: string;
  email_verified: boolean;
  name?: string;
  picture?: string;
  sub: string;
}

export interface PasskeyJSON {
  aaguid?: string;
  created_at: string;
  device_name?: string;
  id: string;
  last_used_at?: string;
  name: string;
}

export interface PasskeyLoginBeginRequest {
  email?: string;
}

export type PasskeyLoginBeginResponseOptions = {[key: string]: unknown};

export interface PasskeyLoginBeginResponse {
  challenge_id: string;
  options: PasskeyLoginBeginResponseOptions;
}

export type PasskeyLoginFinishRequestCredential = {[key: string]: unknown};

export interface PasskeyLoginFinishRequest {
  challenge_id: string;
  credential: PasskeyLoginFinishRequestCredential;
}

export interface PasskeyLoginFinishResponse {
  display_name?: string;
  email: string;
  email_verified: boolean;
  id: string;
  role: string;
}

export type PasskeyRegisterBeginResponseOptions = {[key: string]: unknown};

export interface PasskeyRegisterBeginResponse {
  challenge_id: string;
  options: PasskeyRegisterBeginResponseOptions;
}

export type PasskeyRegisterFinishRequestCredential = {[key: string]: unknown};

export interface PasskeyRegisterFinishRequest {
  credential: PasskeyRegisterFinishRequestCredential;
  name?: string;
}

export interface PasskeyRegisterFinishResponse {
  created_at: string;
  id: string;
  name: string;
}

export interface SessionUserJSON {
  auth_method: string;
  banned: boolean;
  display_name?: string;
  email: string;
  email_verified: boolean;
  id: string;
  role: string;
  /** @nullable */
  scopes: string[] | null;
}

export interface StatusResponse {
  /** @nullable */
  plugins: string[] | null;
  version: string;
}

export interface WebhookCreateRequest {
  /** @nullable */
  events: string[] | null;
  secret?: string;
  url: string;
}

export interface WebhookDeliveryJSON {
  attempt: number;
  created_at: string;
  event_type: string;
  id: string;
  response_body?: string;
  status_code?: number;
  success: boolean;
  webhook_id: string;
}

export interface WebhookJSON {
  active: boolean;
  created_at: string;
  /** @nullable */
  events: string[] | null;
  id: string;
  updated_at: string;
  url: string;
}

export interface WebhookShowResponse {
  /** @nullable */
  recent_deliveries: WebhookDeliveryJSON[] | null;
  webhook: WebhookJSON;
}

export interface WebhookUpdateRequest {
  active?: boolean;
  events?: string[];
  secret?: string;
  url?: string;
}

export type AdminListAuditParams = {
/**
 * Page size.
 */
limit?: number;
/**
 * Pagination offset.
 */
offset?: number;
/**
 * Filter to a single user.
 */
user_id?: string;
/**
 * Filter to a single event_type.
 */
type?: string;
};

export type AdminListSessionsParams = {
/**
 * Filter to a single user.
 */
user_id?: string;
/**
 * Page size.
 */
limit?: number;
/**
 * Pagination offset.
 */
offset?: number;
};

export type AdminListUsersParams = {
/**
 * Page size (default 50, capped at 100).
 */
limit?: number;
/**
 * Pagination offset.
 */
offset?: number;
/**
 * Page number (alternate to limit/offset; 1-based).
 */
page?: number;
/**
 * Page size (alternate to limit).
 */
per_page?: number;
/**
 * Substring match on email or display_name.
 */
search?: string;
};

export type Oauth2AuthorizeParams = {
/**
 * Must be "code".
 */
response_type?: string;
/**
 * Registered client_id.
 */
client_id?: string;
/**
 * One of the client's registered redirect URIs.
 */
redirect_uri?: string;
/**
 * PKCE challenge.
 */
code_challenge?: string;
/**
 * PKCE method (S256 only).
 */
code_challenge_method?: string;
/**
 * Caller-supplied state echoed in the redirect.
 */
state?: string;
/**
 * OIDC nonce; included in id_token.
 */
nonce?: string;
/**
 * Space-separated requested scopes.
 */
scope?: string;
};

export type Oauth2AuthorizePostBodyOne = { [key: string]: unknown };

export type Oauth2AuthorizePostBodyTwo = { [key: string]: unknown };

export type Oauth2DeviceVerifyBodyOne = { [key: string]: unknown };

export type Oauth2DeviceVerifyBodyTwo = { [key: string]: unknown };

export type Oauth2DeviceAuthorizationBody = { [key: string]: unknown };

export type Oauth2IntrospectBody = { [key: string]: unknown };

export type Oauth2DynamicClientRegisterBody = { [key: string]: unknown };

export type Oauth2RevokeBody = { [key: string]: unknown };

export type Oauth2TokenBodyOne = { [key: string]: unknown };

export type Oauth2TokenBodyTwo = { [key: string]: unknown };

export type OauthAuthorizeParams = {
/**
 * Optional URL to navigate to after callback.
 */
redirect_url?: string;
};

export type OauthCallbackParams = {
/**
 * Authorization code.
 */
code?: string;
/**
 * State stored at /authorize.
 */
state?: string;
};

export type OauthLinkParams = {
/**
 * Optional URL to navigate to after callback.
 */
redirect_url?: string;
};

export type WebhookListDeliveriesParams = {
/**
 * Max rows (default 100, capped at 1000).
 */
limit?: number;
};

/**
 * Returned even when no caller is authenticated; suited to relying parties verifying tokens out of band.
 * @summary Public JWKS document for the loaded asymmetric signer
 */
export const getAsymJWKSUrl = () => {




  return `/.well-known/jwks.json`
}

export const asymJWKS = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getAsymJWKSUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary RFC 8414 authorization server metadata
 */
export const getOauth2AuthServerMetadataUrl = () => {




  return `/.well-known/oauth-authorization-server`
}

export const oauth2AuthServerMetadata = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOauth2AuthServerMetadataUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary OpenID Provider discovery document
 */
export const getOidcDiscoveryUrl = () => {




  return `/.well-known/openid-configuration`
}

export const oidcDiscovery = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOidcDiscoveryUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * Always responds 200 to prevent user enumeration.
 * @summary Email a single-use unlock token
 */
export const getLockoutUnlockRequestUrl = () => {




  return `/account/request-unlock`
}

export const lockoutUnlockRequest = async (lockoutUnlockReqRequest: LockoutUnlockReqRequest, options?: RequestInit): Promise<LockoutUnlockReqResponse> => {

  return customFetch<LockoutUnlockReqResponse>(getLockoutUnlockRequestUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      lockoutUnlockReqRequest,)
  }
);}



/**
 * @summary Consume an unlock token to clear an account lock
 */
export const getLockoutUnlockUrl = () => {




  return `/account/unlock`
}

export const lockoutUnlock = async (lockoutUnlockRequest: LockoutUnlockRequest, options?: RequestInit): Promise<LockoutUnlockResponse> => {

  return customFetch<LockoutUnlockResponse>(getLockoutUnlockUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      lockoutUnlockRequest,)
  }
);}



/**
 * @summary List audit-log entries with optional filters
 */
export const getAdminListAuditUrl = (params?: AdminListAuditParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/audit?${stringifiedParams}` : `/admin/audit`
}

export const adminListAudit = async (params?: AdminListAuditParams, options?: RequestInit): Promise<AdminListAuditResponse> => {

  return customFetch<AdminListAuditResponse>(getAdminListAuditUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary List sessions, optionally filtered by user_id
 */
export const getAdminListSessionsUrl = (params?: AdminListSessionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/sessions?${stringifiedParams}` : `/admin/sessions`
}

export const adminListSessions = async (params?: AdminListSessionsParams, options?: RequestInit): Promise<AdminListSessionsResponse> => {

  return customFetch<AdminListSessionsResponse>(getAdminListSessionsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Terminate a single session by id
 */
export const getAdminDeleteSessionUrl = (id: string,) => {




  return `/admin/sessions/${id}`
}

export const adminDeleteSession = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getAdminDeleteSessionUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}



/**
 * @summary List users with optional search/pagination
 */
export const getAdminListUsersUrl = (params?: AdminListUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/users?${stringifiedParams}` : `/admin/users`
}

export const adminListUsers = async (params?: AdminListUsersParams, options?: RequestInit): Promise<AdminListUsersResponse> => {

  return customFetch<AdminListUsersResponse>(getAdminListUsersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Hard-delete a user (refuses self-delete)
 */
export const getAdminDeleteUserUrl = (id: string,) => {




  return `/admin/users/${id}`
}

export const adminDeleteUser = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getAdminDeleteUserUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}



/**
 * @summary Fetch a single user
 */
export const getAdminGetUserUrl = (id: string,) => {




  return `/admin/users/${id}`
}

export const adminGetUser = async (id: string, options?: RequestInit): Promise<AdminUserJSON> => {

  return customFetch<AdminUserJSON>(getAdminGetUserUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Update display_name and/or role
 */
export const getAdminPatchUserUrl = (id: string,) => {




  return `/admin/users/${id}`
}

export const adminPatchUser = async (id: string,
    adminPatchUserRequest: AdminPatchUserRequest, options?: RequestInit): Promise<AdminUserJSON> => {

  return customFetch<AdminUserJSON>(getAdminPatchUserUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      adminPatchUserRequest,)
  }
);}



/**
 * @summary Alias for PATCH /admin/users/{id} (Rust parity)
 */
export const getAdminPutUserUrl = (id: string,) => {




  return `/admin/users/${id}`
}

export const adminPutUser = async (id: string,
    adminPatchUserRequest: AdminPatchUserRequest, options?: RequestInit): Promise<AdminUserJSON> => {

  return customFetch<AdminUserJSON>(getAdminPutUserUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      adminPatchUserRequest,)
  }
);}



/**
 * @summary Ban a user; revokes their sessions
 */
export const getAdminBanUserUrl = (id: string,) => {




  return `/admin/users/${id}/ban`
}

export const adminBanUser = async (id: string,
    adminBanRequest: AdminBanRequest, options?: RequestInit): Promise<AdminUserJSON> => {

  return customFetch<AdminUserJSON>(getAdminBanUserUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      adminBanRequest,)
  }
);}



/**
 * @summary Issue a session cookie for the target user
 */
export const getAdminImpersonateUrl = (id: string,) => {




  return `/admin/users/${id}/impersonate`
}

export const adminImpersonate = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getAdminImpersonateUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}



/**
 * @summary Revoke every session for a user
 */
export const getAdminDeleteUserSessionsUrl = (id: string,) => {




  return `/admin/users/${id}/sessions`
}

export const adminDeleteUserSessions = async (id: string, options?: RequestInit): Promise<AdminDeleteSessionsResponse> => {

  return customFetch<AdminDeleteSessionsResponse>(getAdminDeleteUserSessionsUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}



/**
 * @summary Lift a previous ban
 */
export const getAdminUnbanUserUrl = (id: string,) => {




  return `/admin/users/${id}/unban`
}

export const adminUnbanUser = async (id: string, options?: RequestInit): Promise<AdminUserJSON> => {

  return customFetch<AdminUserJSON>(getAdminUnbanUserUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}



/**
 * @summary Force-unlock a user (admin)
 */
export const getLockoutAdminUnlockUrl = (id: string,) => {




  return `/admin/users/${id}/unlock`
}

export const lockoutAdminUnlock = async (id: string, options?: RequestInit): Promise<LockoutUnlockResponse> => {

  return customFetch<LockoutUnlockResponse>(getLockoutAdminUnlockUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}



/**
 * @summary List the caller's API keys (no secrets)
 */
export const getApiKeyListUrl = () => {




  return `/api-keys`
}

export const apiKeyList = async ( options?: RequestInit): Promise<ApiKeyJSON[]> => {

  return customFetch<ApiKeyJSON[]>(getApiKeyListUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Create a new API key (plaintext secret returned once)
 */
export const getApiKeyCreateUrl = () => {




  return `/api-keys`
}

export const apiKeyCreate = async (apiKeyCreateRequest: ApiKeyCreateRequest, options?: RequestInit): Promise<ApiKeyCreateResponse> => {

  return customFetch<ApiKeyCreateResponse>(getApiKeyCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      apiKeyCreateRequest,)
  }
);}



/**
 * @summary Revoke an API key the caller owns
 */
export const getApiKeyDeleteUrl = (id: string,) => {




  return `/api-keys/${id}`
}

export const apiKeyDelete = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getApiKeyDeleteUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}



/**
 * Verifies the current password, stores the new hash, revokes other sessions, re-issues a fresh cookie for the caller.
 * @summary Rotate the caller's password
 */
export const getEmailPasswordChangePasswordUrl = () => {




  return `/change-password`
}

export const emailPasswordChangePassword = async (emailPasswordChangePasswordRequest: EmailPasswordChangePasswordRequest, options?: RequestInit): Promise<EmailPasswordChangePasswordResponse> => {

  return customFetch<EmailPasswordChangePasswordResponse>(getEmailPasswordChangePasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emailPasswordChangePasswordRequest,)
  }
);}



/**
 * @summary Return the host configuration subset exposed for clients
 */
export const getConfigUrl = () => {




  return `/config`
}

export const config = async ( options?: RequestInit): Promise<ConfigResponse> => {

  return customFetch<ConfigResponse>(getConfigUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * Always responds 200 to prevent user enumeration.
 * @summary Email a single-use password-reset token
 */
export const getEmailPasswordForgotPasswordUrl = () => {




  return `/forgot-password`
}

export const emailPasswordForgotPassword = async (emailForgotPasswordRequest: EmailForgotPasswordRequest, options?: RequestInit): Promise<EmailForgotPasswordResponse> => {

  return customFetch<EmailForgotPasswordResponse>(getEmailPasswordForgotPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emailForgotPasswordRequest,)
  }
);}



/**
 * @summary List currently locked accounts (admin)
 */
export const getLockoutStateUrl = () => {




  return `/lockout/state`
}

export const lockoutState = async ( options?: RequestInit): Promise<LockoutStateResponse> => {

  return customFetch<LockoutStateResponse>(getLockoutStateUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * On success returns the user; if MFA is enabled returns require_mfa + pending_session_id.
 * @summary Verify password and start a session
 */
export const getEmailPasswordLoginUrl = () => {




  return `/login`
}

export const emailPasswordLogin = async (emailPasswordLoginRequest: EmailPasswordLoginRequest, options?: RequestInit): Promise<EmailPasswordLoginResponse | EmailPasswordLoginMfaResponse> => {

  return customFetch<EmailPasswordLoginResponse | EmailPasswordLoginMfaResponse>(getEmailPasswordLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emailPasswordLoginRequest,)
  }
);}



/**
 * @summary Revoke the current session
 */
export const getEmailPasswordLogoutUrl = () => {




  return `/logout`
}

export const emailPasswordLogout = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getEmailPasswordLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



/**
 * Always responds 200 to prevent user enumeration; the link is delivered via the configured Mailer.
 * @summary Email a single-use sign-in link
 */
export const getMagicLinkSendUrl = () => {




  return `/magic-link/send`
}

export const magicLinkSend = async (magicLinkSendRequest: MagicLinkSendRequest, options?: RequestInit): Promise<MagicLinkSendResponse> => {

  return customFetch<MagicLinkSendResponse>(getMagicLinkSendUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      magicLinkSendRequest,)
  }
);}



/**
 * @summary Exchange a magic-link token for a session
 */
export const getMagicLinkVerifyUrl = () => {




  return `/magic-link/verify`
}

export const magicLinkVerify = async (magicLinkVerifyRequest: MagicLinkVerifyRequest, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getMagicLinkVerifyUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      magicLinkVerifyRequest,)
  }
);}



/**
 * Currently only display_name is mutable.
 * @summary Update the caller's profile
 */
export const getEmailPasswordPatchMeUrl = () => {




  return `/me`
}

export const emailPasswordPatchMe = async (emailPasswordPatchMeRequest: EmailPasswordPatchMeRequest, options?: RequestInit): Promise<EmailPasswordPatchMeResponse> => {

  return customFetch<EmailPasswordPatchMeResponse>(getEmailPasswordPatchMeUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emailPasswordPatchMeRequest,)
  }
);}



/**
 * @summary Return the count of unused backup codes
 */
export const getMfaBackupCodesCountUrl = () => {




  return `/mfa/backup-codes`
}

export const mfaBackupCodesCount = async ( options?: RequestInit): Promise<MfaBackupCodesCountResponse> => {

  return customFetch<MfaBackupCodesCountResponse>(getMfaBackupCodesCountUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Replace the user's backup codes; returns the new set once
 */
export const getMfaRegenerateBackupCodesUrl = () => {




  return `/mfa/backup-codes/regenerate`
}

export const mfaRegenerateBackupCodes = async ( options?: RequestInit): Promise<MfaRegenerateResponse> => {

  return customFetch<MfaRegenerateResponse>(getMfaRegenerateBackupCodesUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



/**
 * @summary Remove the user's TOTP secret + backup codes
 */
export const getMfaTOTPDeleteUrl = () => {




  return `/mfa/totp`
}

export const mfaTOTPDelete = async ( options?: RequestInit): Promise<MfaMessageResponse> => {

  return customFetch<MfaMessageResponse>(getMfaTOTPDeleteUrl(),
  {
    ...options,
    method: 'DELETE'


  }
);}



/**
 * @summary Verify the freshly-provisioned TOTP and activate it
 */
export const getMfaTOTPConfirmUrl = () => {




  return `/mfa/totp/confirm`
}

export const mfaTOTPConfirm = async (mfaConfirmRequest: MfaConfirmRequest, options?: RequestInit): Promise<MfaMessageResponse> => {

  return customFetch<MfaMessageResponse>(getMfaTOTPConfirmUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      mfaConfirmRequest,)
  }
);}



/**
 * Wipes any prior secret/backup codes for this user, then issues a fresh QR + backup-code set.
 * @summary Provision a new TOTP secret + backup codes (unverified)
 */
export const getMfaTOTPSetupUrl = () => {




  return `/mfa/totp/setup`
}

export const mfaTOTPSetup = async ( options?: RequestInit): Promise<MfaSetupResponse> => {

  return customFetch<MfaSetupResponse>(getMfaTOTPSetupUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



/**
 * @summary Consume a pending session (TOTP or backup code)
 */
export const getMfaVerifyUrl = () => {




  return `/mfa/verify`
}

export const mfaVerify = async (mfaVerifyRequest: MfaVerifyRequest, options?: RequestInit): Promise<MfaVerifyResponse> => {

  return customFetch<MfaVerifyResponse>(getMfaVerifyUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      mfaVerifyRequest,)
  }
);}



/**
 * @summary List the caller's linked OAuth accounts
 */
export const getOauthListAccountsUrl = () => {




  return `/oauth/accounts`
}

export const oauthListAccounts = async ( options?: RequestInit): Promise<OauthAccountJSON[]> => {

  return customFetch<OauthAccountJSON[]>(getOauthListAccountsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Authorization endpoint — returns either a redirect URL or a consent payload
 */
export const getOauth2AuthorizeUrl = (params?: Oauth2AuthorizeParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/oauth/authorize?${stringifiedParams}` : `/oauth/authorize`
}

export const oauth2Authorize = async (params?: Oauth2AuthorizeParams, options?: RequestInit): Promise<Oauth2AuthorizeRedirect | Oauth2ConsentPayload> => {

  return customFetch<Oauth2AuthorizeRedirect | Oauth2ConsentPayload>(getOauth2AuthorizeUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * Identical semantics to the GET form; some clients prefer to submit the request as application/x-www-form-urlencoded.
 * @summary POST variant of /oauth/authorize (Rust parity)
 */
export const getOauth2AuthorizePostUrl = () => {




  return `/oauth/authorize`
}

export const oauth2AuthorizePost = async (oauth2AuthorizePostBody: Oauth2AuthorizePostBodyOne | Oauth2AuthorizePostBodyTwo, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOauth2AuthorizePostUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: JSON.stringify(
      oauth2AuthorizePostBody,)
  }
);}



/**
 * Renders or proxies the user-facing prompt where the user enters the user_code printed on the device. Body shape is implementation-defined.
 * @summary Browser landing for the device flow user-code prompt (Rust parity)
 */
export const getOauth2DeviceVerifyGetUrl = () => {




  return `/oauth/device`
}

export const oauth2DeviceVerifyGet = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOauth2DeviceVerifyGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary User-facing endpoint to enter a user_code (RFC 8628)
 */
export const getOauth2DeviceVerifyUrl = () => {




  return `/oauth/device`
}

export const oauth2DeviceVerify = async (oauth2DeviceVerifyBody: Oauth2DeviceVerifyBodyOne | Oauth2DeviceVerifyBodyTwo, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOauth2DeviceVerifyUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: JSON.stringify(
      oauth2DeviceVerifyBody,)
  }
);}



/**
 * @summary RFC 8628 device-authorization endpoint
 */
export const getOauth2DeviceAuthorizationUrl = () => {




  return `/oauth/device/code`
}

export const oauth2DeviceAuthorization = async (oauth2DeviceAuthorizationBody: Oauth2DeviceAuthorizationBody, options?: RequestInit): Promise<void> => {
    const formUrlEncoded = new URLSearchParams();

  return customFetch<void>(getOauth2DeviceAuthorizationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body:
      formUrlEncoded,
  }
);}



/**
 * Caller authenticates as a confidential client.
 * @summary RFC 7662 token introspection
 */
export const getOauth2IntrospectUrl = () => {




  return `/oauth/introspect`
}

export const oauth2Introspect = async (oauth2IntrospectBody: Oauth2IntrospectBody, options?: RequestInit): Promise<void> => {
    const formUrlEncoded = new URLSearchParams();

  return customFetch<void>(getOauth2IntrospectUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body:
      formUrlEncoded,
  }
);}



/**
 * Public dynamic client registration endpoint. Disabled by default; opt in via plugin Config.DCREnabled. When DCRRequireInitialAccessToken is true (default), the request must carry an admin-issued Bearer token in the Authorization header.
 * @summary Register an OAuth2 client (RFC 7591)
 */
export const getOauth2DynamicClientRegisterUrl = () => {




  return `/oauth/register`
}

export const oauth2DynamicClientRegister = async (oauth2DynamicClientRegisterBody: Oauth2DynamicClientRegisterBody, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOauth2DynamicClientRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      oauth2DynamicClientRegisterBody,)
  }
);}



/**
 * Idempotent: unknown / already-revoked / malformed tokens still return 200.
 * @summary RFC 7009 revocation
 */
export const getOauth2RevokeUrl = () => {




  return `/oauth/revoke`
}

export const oauth2Revoke = async (oauth2RevokeBody: Oauth2RevokeBody, options?: RequestInit): Promise<void> => {
    const formUrlEncoded = new URLSearchParams();

  return customFetch<void>(getOauth2RevokeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body:
      formUrlEncoded,
  }
);}



/**
 * Accepts authorization_code, refresh_token, client_credentials, and urn:ietf:params:oauth:grant-type:device_code grants. Body is application/x-www-form-urlencoded or application/json.
 * @summary Token endpoint (RFC 6749 §3.2)
 */
export const getOauth2TokenUrl = () => {




  return `/oauth/token`
}

export const oauth2Token = async (oauth2TokenBody: Oauth2TokenBodyOne | Oauth2TokenBodyTwo, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOauth2TokenUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: JSON.stringify(
      oauth2TokenBody,)
  }
);}



/**
 * @summary Unlink a provider; refuses if it would lock out the caller
 */
export const getOauthUnlinkUrl = (provider: string,) => {




  return `/oauth/${provider}`
}

export const oauthUnlink = async (provider: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOauthUnlinkUrl(provider),
  {
    ...options,
    method: 'DELETE'


  }
);}



/**
 * Persists state and redirects (302) the user-agent to the provider's authorization endpoint.
 * @summary Begin authorization-code flow; redirects to provider
 */
export const getOauthAuthorizeUrl = (provider: string,
    params?: OauthAuthorizeParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/oauth/${provider}/authorize?${stringifiedParams}` : `/oauth/${provider}/authorize`
}

export const oauthAuthorize = async (provider: string,
    params?: OauthAuthorizeParams, options?: RequestInit): Promise<unknown> => {

  return customFetch<unknown>(getOauthAuthorizeUrl(provider,params),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Exchange the auth code; create or attach the user; issue a session
 */
export const getOauthCallbackUrl = (provider: string,
    params?: OauthCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/oauth/${provider}/callback?${stringifiedParams}` : `/oauth/${provider}/callback`
}

export const oauthCallback = async (provider: string,
    params?: OauthCallbackParams, options?: RequestInit): Promise<OauthCallbackResponse> => {

  return customFetch<OauthCallbackResponse>(getOauthCallbackUrl(provider,params),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * Used by SPAs that prefer to POST the {code, state} pair from a hash fragment rather than appearing in the URL. Body is application/json or application/x-www-form-urlencoded.
 * @summary JSON-body variant of GET /oauth/{provider}/callback (Rust parity)
 */
export const getOauthCallbackPostUrl = (provider: string,) => {




  return `/oauth/${provider}/callback`
}

export const oauthCallbackPost = async (provider: string,
    oauthCallbackBody: OauthCallbackBody, options?: RequestInit): Promise<OauthCallbackResponse> => {

  return customFetch<OauthCallbackResponse>(getOauthCallbackPostUrl(provider),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      oauthCallbackBody,)
  }
);}



/**
 * @summary Start a link flow for an already-authenticated user
 */
export const getOauthLinkUrl = (provider: string,
    params?: OauthLinkParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/oauth/${provider}/link?${stringifiedParams}` : `/oauth/${provider}/link`
}

export const oauthLink = async (provider: string,
    params?: OauthLinkParams, options?: RequestInit): Promise<OauthLinkResponse> => {

  return customFetch<OauthLinkResponse>(getOauthLinkUrl(provider,params),
  {
    ...options,
    method: 'POST'


  }
);}



/**
 * The repository surface only exposes a banned-clients list; non-banned clients are fetched individually by client_id.
 * @summary List banned OAuth2 clients (admin)
 */
export const getOauth2ListBannedClientsUrl = () => {




  return `/oauth2/clients`
}

export const oauth2ListBannedClients = async ( options?: RequestInit): Promise<Oauth2BannedClientsResponse> => {

  return customFetch<Oauth2BannedClientsResponse>(getOauth2ListBannedClientsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * For confidential clients (is_public=false) a fresh client_secret is generated and returned exactly once.
 * @summary Register a new OAuth2 client (admin)
 */
export const getOauth2CreateClientUrl = () => {




  return `/oauth2/clients`
}

export const oauth2CreateClient = async (oauth2CreateClientRequest: Oauth2CreateClientRequest, options?: RequestInit): Promise<Oauth2CreateClientResponse> => {

  return customFetch<Oauth2CreateClientResponse>(getOauth2CreateClientUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      oauth2CreateClientRequest,)
  }
);}



/**
 * Hard delete is not exposed because issued tokens still reference the client.
 * @summary Soft-delete (ban) a client
 */
export const getOauth2DeleteClientUrl = (id: string,) => {




  return `/oauth2/clients/${id}`
}

export const oauth2DeleteClient = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOauth2DeleteClientUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}



/**
 * @summary Fetch a registered OAuth2 client
 */
export const getOauth2GetClientUrl = (id: string,) => {




  return `/oauth2/clients/${id}`
}

export const oauth2GetClient = async (id: string, options?: RequestInit): Promise<Oauth2ClientJSON> => {

  return customFetch<Oauth2ClientJSON>(getOauth2GetClientUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Ban / unban or rotate the public key of a client (admin)
 */
export const getOauth2PatchClientUrl = (id: string,) => {




  return `/oauth2/clients/${id}`
}

export const oauth2PatchClient = async (id: string,
    oauth2PatchClientRequest: Oauth2PatchClientRequest, options?: RequestInit): Promise<Oauth2ClientJSON> => {

  return customFetch<Oauth2ClientJSON>(getOauth2PatchClientUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      oauth2PatchClientRequest,)
  }
);}



/**
 * @summary Approve or deny a pending /authorize
 */
export const getOauth2ConsentUrl = () => {




  return `/oauth2/consent`
}

export const oauth2Consent = async (oauth2ConsentRequest: Oauth2ConsentRequest, options?: RequestInit): Promise<Oauth2AuthorizeRedirect> => {

  return customFetch<Oauth2AuthorizeRedirect>(getOauth2ConsentUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      oauth2ConsentRequest,)
  }
);}



/**
 * @summary Start a passkey assertion; supports discoverable flow
 */
export const getPasskeyLoginBeginUrl = () => {




  return `/passkey/login/begin`
}

export const passkeyLoginBegin = async (passkeyLoginBeginRequest: PasskeyLoginBeginRequest, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getPasskeyLoginBeginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      passkeyLoginBeginRequest,)
  }
);}



/**
 * @summary Verify the assertion and start a session
 */
export const getPasskeyLoginFinishUrl = () => {




  return `/passkey/login/finish`
}

export const passkeyLoginFinish = async (passkeyLoginFinishRequest: PasskeyLoginFinishRequest, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getPasskeyLoginFinishUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      passkeyLoginFinishRequest,)
  }
);}



/**
 * @summary List the caller's stored passkeys
 */
export const getPasskeyListUrl = () => {




  return `/passkeys`
}

export const passkeyList = async ( options?: RequestInit): Promise<PasskeyJSON[]> => {

  return customFetch<PasskeyJSON[]>(getPasskeyListUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Start passkey registration; return CredentialCreation options
 */
export const getPasskeyRegisterBeginUrl = () => {




  return `/passkeys/register/begin`
}

export const passkeyRegisterBegin = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getPasskeyRegisterBeginUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



/**
 * @summary Verify attestation and store the new credential
 */
export const getPasskeyRegisterFinishUrl = () => {




  return `/passkeys/register/finish`
}

export const passkeyRegisterFinish = async (passkeyRegisterFinishRequest: PasskeyRegisterFinishRequest, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getPasskeyRegisterFinishUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      passkeyRegisterFinishRequest,)
  }
);}



/**
 * @summary Delete one of the caller's passkeys
 */
export const getPasskeyDeleteUrl = (id: string,) => {




  return `/passkeys/${id}`
}

export const passkeyDelete = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getPasskeyDeleteUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}



/**
 * Creates a user, hashes the password with Argon2id, issues a session cookie.
 * @summary Register a new user
 */
export const getEmailPasswordRegisterUrl = () => {




  return `/register`
}

export const emailPasswordRegister = async (emailPasswordRegisterRequest: EmailPasswordRegisterRequest, options?: RequestInit): Promise<EmailPasswordRegisterResponse> => {

  return customFetch<EmailPasswordRegisterResponse>(getEmailPasswordRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emailPasswordRegisterRequest,)
  }
);}



/**
 * Always responds 200 to prevent user enumeration.
 * @summary Email a fresh verification link
 */
export const getEmailPasswordResendVerificationUrl = () => {




  return `/resend-verification`
}

export const emailPasswordResendVerification = async (emailResendVerificationRequest: EmailResendVerificationRequest, options?: RequestInit): Promise<EmailResendVerificationResponse> => {

  return customFetch<EmailResendVerificationResponse>(getEmailPasswordResendVerificationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emailResendVerificationRequest,)
  }
);}



/**
 * @summary Consume a password-reset token and set a new password
 */
export const getEmailPasswordResetPasswordUrl = () => {




  return `/reset-password`
}

export const emailPasswordResetPassword = async (emailResetPasswordRequest: EmailResetPasswordRequest, options?: RequestInit): Promise<EmailResetPasswordResponse> => {

  return customFetch<EmailResetPasswordResponse>(getEmailPasswordResetPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emailResetPasswordRequest,)
  }
);}



/**
 * @summary Return the current authenticated user
 */
export const getEmailPasswordSessionUrl = () => {




  return `/session`
}

export const emailPasswordSession = async ( options?: RequestInit): Promise<EmailPasswordSessionResponse> => {

  return customFetch<EmailPasswordSessionResponse>(getEmailPasswordSessionUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Return the names of registered plugins (admin)
 */
export const getStatusUrl = () => {




  return `/status`
}

export const status = async ( options?: RequestInit): Promise<StatusResponse> => {

  return customFetch<StatusResponse>(getStatusUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Exchange email+password for an access+refresh token pair
 */
export const getBearerIssueTokenUrl = () => {




  return `/token`
}

export const bearerIssueToken = async (bearerTokenRequest: BearerTokenRequest, options?: RequestInit): Promise<BearerTokenResponse> => {

  return customFetch<BearerTokenResponse>(getBearerIssueTokenUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bearerTokenRequest,)
  }
);}



/**
 * Reuse of a previously rotated refresh token revokes the entire family.
 * @summary Rotate the refresh token; re-mint access+refresh
 */
export const getBearerRefreshUrl = () => {




  return `/token/refresh`
}

export const bearerRefresh = async (bearerRefreshRequest: BearerRefreshRequest, options?: RequestInit): Promise<BearerTokenResponse> => {

  return customFetch<BearerTokenResponse>(getBearerRefreshUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bearerRefreshRequest,)
  }
);}



/**
 * @summary Revoke a refresh-token family
 */
export const getBearerRevokeUrl = () => {




  return `/token/revoke`
}

export const bearerRevoke = async (bearerRevokeRequest: BearerRevokeRequest, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getBearerRevokeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bearerRevokeRequest,)
  }
);}



/**
 * @summary Standard OIDC UserInfo for the authenticated caller
 */
export const getOidcUserInfoUrl = () => {




  return `/userinfo`
}

export const oidcUserInfo = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOidcUserInfoUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Consume a verification token issued by /resend-verification
 */
export const getEmailPasswordVerifyEmailUrl = () => {




  return `/verify-email`
}

export const emailPasswordVerifyEmail = async (emailVerifyRequest: EmailVerifyRequest, options?: RequestInit): Promise<EmailVerifyResponse> => {

  return customFetch<EmailVerifyResponse>(getEmailPasswordVerifyEmailUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      emailVerifyRequest,)
  }
);}



/**
 * @summary List webhooks (admin)
 */
export const getWebhookListUrl = () => {




  return `/webhooks`
}

export const webhookList = async ( options?: RequestInit): Promise<WebhookJSON[]> => {

  return customFetch<WebhookJSON[]>(getWebhookListUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Create a webhook; secret is returned exactly once
 */
export const getWebhookCreateUrl = () => {




  return `/webhooks`
}

export const webhookCreate = async (webhookCreateRequest: WebhookCreateRequest, options?: RequestInit): Promise<WebhookJSON> => {

  return customFetch<WebhookJSON>(getWebhookCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      webhookCreateRequest,)
  }
);}



/**
 * @summary Delete a webhook
 */
export const getWebhookDeleteUrl = (id: string,) => {




  return `/webhooks/${id}`
}

export const webhookDelete = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getWebhookDeleteUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}



/**
 * @summary Fetch a single webhook with its recent_deliveries (no secret)
 */
export const getWebhookGetUrl = (id: string,) => {




  return `/webhooks/${id}`
}

export const webhookGet = async (id: string, options?: RequestInit): Promise<WebhookShowResponse> => {

  return customFetch<WebhookShowResponse>(getWebhookGetUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Update url/events/active and optionally rotate the secret
 */
export const getWebhookUpdateUrl = (id: string,) => {




  return `/webhooks/${id}`
}

export const webhookUpdate = async (id: string,
    webhookUpdateRequest: WebhookUpdateRequest, options?: RequestInit): Promise<WebhookJSON> => {

  return customFetch<WebhookJSON>(getWebhookUpdateUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      webhookUpdateRequest,)
  }
);}



/**
 * @summary Alias for PATCH /webhooks/{id} (Rust parity)
 */
export const getWebhookPutUrl = (id: string,) => {




  return `/webhooks/${id}`
}

export const webhookPut = async (id: string,
    webhookUpdateRequest: WebhookUpdateRequest, options?: RequestInit): Promise<WebhookJSON> => {

  return customFetch<WebhookJSON>(getWebhookPutUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      webhookUpdateRequest,)
  }
);}



/**
 * @summary List recent delivery attempts for a webhook
 */
export const getWebhookListDeliveriesUrl = (id: string,
    params?: WebhookListDeliveriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/webhooks/${id}/deliveries?${stringifiedParams}` : `/webhooks/${id}/deliveries`
}

export const webhookListDeliveries = async (id: string,
    params?: WebhookListDeliveriesParams, options?: RequestInit): Promise<WebhookDeliveryJSON[]> => {

  return customFetch<WebhookDeliveryJSON[]>(getWebhookListDeliveriesUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Enqueue a synthetic webhook.test delivery
 */
export const getWebhookTestUrl = (id: string,) => {




  return `/webhooks/${id}/test`
}

export const webhookTest = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getWebhookTestUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}
