/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * yauth API
 * Modular, plugin-based authentication API for Axum applications.
 * OpenAPI spec version: 0.2.5
 */
import { customFetch } from './mutator';
export interface AccountLockoutMessageResponse {
  message: string;
}

/**
 * Session info returned by admin list endpoint.
 */
export interface AdminSessionInfo {
  created_at: string;
  expires_at: string;
  id: string;
  /** @nullable */
  ip_address?: string | null;
  /** @nullable */
  user_agent?: string | null;
  user_id: string;
}

/**
 * User info returned by admin list endpoint.
 */
export interface AdminUserInfo {
  banned: boolean;
  /** @nullable */
  banned_reason?: string | null;
  /** @nullable */
  banned_until?: string | null;
  created_at: string;
  /** @nullable */
  display_name?: string | null;
  email: string;
  email_verified: boolean;
  id: string;
  role: string;
  updated_at: string;
}

export interface ApiKeyResponse {
  created_at: string;
  /** @nullable */
  expires_at?: string | null;
  id: string;
  /** @nullable */
  last_used_at?: string | null;
  name: string;
  prefix: string;
  /** @nullable */
  scopes?: string[] | null;
}

/**
 * Server-side auth configuration exposed to frontends via `GET /config`.
 */
export interface AuthConfigResponse {
  /** Whether new user registration is allowed. */
  allow_signups: boolean;
  /** Whether newly registered users must verify their email before logging in. */
  require_email_verification: boolean;
}

export type AuthMethod = typeof AuthMethod[keyof typeof AuthMethod];


export const AuthMethod = {
  Session: 'Session',
  Bearer: 'Bearer',
  ApiKey: 'ApiKey',
} as const;

export interface AuthUser {
  auth_method: AuthMethod;
  banned: boolean;
  /** @nullable */
  display_name?: string | null;
  email: string;
  email_verified: boolean;
  id: string;
  role: string;
  /** @nullable */
  scopes?: string[] | null;
}

export interface AuthorizeQuery {
  /** @nullable */
  redirect_url?: string | null;
}

export interface AuthorizeResponse {
  auth_url: string;
}

export interface BackupCodeCountResponse {
  /** @minimum 0 */
  remaining: number;
}

export interface BackupCodesResponse {
  backup_codes: string[];
}

export interface BanRequest {
  /** @nullable */
  reason?: string | null;
  /** @nullable */
  until?: string | null;
}

export interface CallbackBody {
  code: string;
  state: string;
}

export interface ChangePasswordRequest {
  current_password: string;
  new_password: string;
}

export interface ConfirmTotpRequest {
  code: string;
}

export interface CreateApiKeyRequest {
  /**
     * @minimum 0
     * @nullable
     */
  expires_in_days?: number | null;
  name: string;
  /** @nullable */
  scopes?: string[] | null;
}

export interface CreateApiKeyResponse {
  created_at: string;
  /** @nullable */
  expires_at?: string | null;
  id: string;
  key: string;
  name: string;
  prefix: string;
  /** @nullable */
  scopes?: string[] | null;
}

export interface CreateWebhookRequest {
  events: string[];
  /** @nullable */
  secret?: string | null;
  url: string;
}

export interface ForgotPasswordRequest {
  email: string;
}

export interface ListSessionsQuery {
  /**
     * @minimum 0
     * @nullable
     */
  page?: number | null;
  /**
     * @minimum 0
     * @nullable
     */
  per_page?: number | null;
}

export interface ListUsersQuery {
  /**
     * @minimum 0
     * @nullable
     */
  page?: number | null;
  /**
     * @minimum 0
     * @nullable
     */
  per_page?: number | null;
  /** @nullable */
  search?: string | null;
}

export interface LoginRequest {
  email: string;
  password: string;
  /** @nullable */
  remember_me?: boolean | null;
}

export interface MagicLinkMessageResponse {
  message: string;
}

export interface MagicLinkSendRequest {
  email: string;
}

export interface MagicLinkVerifyRequest {
  token: string;
}

export interface MessageResponse {
  message: string;
}

export interface MfaAuthResponse {
  /** @nullable */
  display_name?: string | null;
  email: string;
  email_verified: boolean;
  user_id: string;
}

export interface MfaMessageResponse {
  message: string;
}

export interface OAuthAccountResponse {
  created_at: string;
  id: string;
  provider: string;
  provider_user_id: string;
}

export interface OAuthAuthResponse {
  /** @nullable */
  display_name?: string | null;
  email: string;
  email_verified: boolean;
  user_id: string;
}

/**
 * Response type for `GET /admin/sessions` (schema-only, used for OpenAPI spec).
 */
export interface PaginatedSessionsResponse {
  /** @minimum 0 */
  page: number;
  /** @minimum 0 */
  per_page: number;
  sessions: AdminSessionInfo[];
  /** @minimum 0 */
  total: number;
}

/**
 * Response type for `GET /admin/users` (schema-only, used for OpenAPI spec).
 */
export interface PaginatedUsersResponse {
  /** @minimum 0 */
  page: number;
  /** @minimum 0 */
  per_page: number;
  /** @minimum 0 */
  total: number;
  users: AdminUserInfo[];
}

export interface PasskeyInfo {
  created_at: string;
  id: string;
  /** @nullable */
  last_used_at?: string | null;
  name: string;
}

export interface PasskeyLoginBeginRequest {
  /** @nullable */
  email?: string | null;
}

export type PasskeyLoginFinishRequestCredential = { [key: string]: unknown };

export interface PasskeyLoginFinishRequest {
  challenge_id: string;
  credential: PasskeyLoginFinishRequestCredential;
}

export interface RefreshRequest {
  refresh_token: string;
}

export type RegisterFinishRequestCredential = { [key: string]: unknown };

export interface RegisterFinishRequest {
  credential: RegisterFinishRequestCredential;
  name: string;
}

export interface RegisterRequest {
  /** @nullable */
  display_name?: string | null;
  email: string;
  password: string;
}

export interface RequestUnlockRequest {
  email: string;
}

export interface ResendVerificationRequest {
  email: string;
}

export interface ResetPasswordRequest {
  password: string;
  token: string;
}

export interface RevokeRequest {
  refresh_token: string;
}

export interface SetupTotpResponse {
  backup_codes: string[];
  otpauth_url: string;
  secret: string;
}

export interface TokenRequest {
  email: string;
  password: string;
  /**
     * Optional space-separated OAuth2 scopes (e.g. "read:runs write:runs").
     * @nullable
     */
  scope?: string | null;
}

export interface TokenResponse {
  access_token: string;
  /** @minimum 0 */
  expires_in: number;
  refresh_token: string;
  token_type: string;
}

export interface UnlockAccountRequest {
  token: string;
}

export interface UpdateProfileRequest {
  /** @nullable */
  display_name?: string | null;
}

export interface UpdateUserRequest {
  /** @nullable */
  display_name?: string | null;
  /** @nullable */
  email_verified?: boolean | null;
  /** @nullable */
  role?: string | null;
}

export interface UpdateWebhookRequest {
  /** @nullable */
  active?: boolean | null;
  /** @nullable */
  events?: string[] | null;
  /** @nullable */
  secret?: string | null;
  /** @nullable */
  url?: string | null;
}

export interface VerifyEmailRequest {
  token: string;
}

export interface VerifyMfaRequest {
  code: string;
  pending_session_id: string;
}

export interface WebhookDeliveryResponse {
  attempt: number;
  created_at: string;
  event_type: string;
  id: string;
  /** @nullable */
  status_code?: number | null;
  success: boolean;
}

export interface WebhookResponse {
  active: boolean;
  created_at: string;
  events: string[];
  id: string;
  updated_at: string;
  url: string;
}

export interface WebhookDetailResponse {
  recent_deliveries: WebhookDeliveryResponse[];
  webhook: WebhookResponse;
}

export type AdminListSessionsParams = {
page?: string;
per_page?: string;
};

export type AdminListUsersParams = {
page?: string;
per_page?: string;
search?: string;
};

export const getOidcJwksUrl = () => {




  return `/.well-known/jwks.json`
}

export const oidcJwks = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOidcJwksUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getOauth2ServerMetadataUrl = () => {




  return `/.well-known/oauth-authorization-server`
}

export const oauth2ServerMetadata = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOauth2ServerMetadataUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getOidcOpenidConfigurationUrl = () => {




  return `/.well-known/openid-configuration`
}

export const oidcOpenidConfiguration = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOidcOpenidConfigurationUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getAccountLockoutRequestUnlockUrl = () => {




  return `/account/request-unlock`
}

export const accountLockoutRequestUnlock = async (requestUnlockRequest: RequestUnlockRequest, options?: RequestInit): Promise<AccountLockoutMessageResponse> => {

  return customFetch<AccountLockoutMessageResponse>(getAccountLockoutRequestUnlockUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      requestUnlockRequest,)
  }
);}



export const getAccountLockoutUnlockUrl = () => {




  return `/account/unlock`
}

export const accountLockoutUnlock = async (unlockAccountRequest: UnlockAccountRequest, options?: RequestInit): Promise<AccountLockoutMessageResponse> => {

  return customFetch<AccountLockoutMessageResponse>(getAccountLockoutUnlockUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      unlockAccountRequest,)
  }
);}



export const getAdminListSessionsUrl = (params?: AdminListSessionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/sessions?${stringifiedParams}` : `/admin/sessions`
}

export const adminListSessions = async (params?: AdminListSessionsParams, options?: RequestInit): Promise<PaginatedSessionsResponse> => {

  return customFetch<PaginatedSessionsResponse>(getAdminListSessionsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getAdminDeleteSessionUrl = (id: string,) => {




  return `/admin/sessions/${id}`
}

export const adminDeleteSession = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getAdminDeleteSessionUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}



export const getAdminListUsersUrl = (params?: AdminListUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/users?${stringifiedParams}` : `/admin/users`
}

export const adminListUsers = async (params?: AdminListUsersParams, options?: RequestInit): Promise<PaginatedUsersResponse> => {

  return customFetch<PaginatedUsersResponse>(getAdminListUsersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export const getAdminGetUserUrl = (id: string,) => {




  return `/admin/users/${id}`
}

export const adminGetUser = async (id: string, options?: RequestInit): Promise<AdminUserInfo> => {

  return customFetch<AdminUserInfo>(getAdminGetUserUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getAdminUpdateUserUrl = (id: string,) => {




  return `/admin/users/${id}`
}

export const adminUpdateUser = async (id: string,
    updateUserRequest: UpdateUserRequest, options?: RequestInit): Promise<AdminUserInfo> => {

  return customFetch<AdminUserInfo>(getAdminUpdateUserUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateUserRequest,)
  }
);}



export const getAdminDeleteUserUrl = (id: string,) => {




  return `/admin/users/${id}`
}

export const adminDeleteUser = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getAdminDeleteUserUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}



export const getAdminBanUserUrl = (id: string,) => {




  return `/admin/users/${id}/ban`
}

export const adminBanUser = async (id: string,
    banRequest: BanRequest, options?: RequestInit): Promise<AdminUserInfo> => {

  return customFetch<AdminUserInfo>(getAdminBanUserUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      banRequest,)
  }
);}



export const getAdminImpersonateUrl = (id: string,) => {




  return `/admin/users/${id}/impersonate`
}

export const adminImpersonate = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getAdminImpersonateUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}



export const getAdminUnbanUserUrl = (id: string,) => {




  return `/admin/users/${id}/unban`
}

export const adminUnbanUser = async (id: string, options?: RequestInit): Promise<AdminUserInfo> => {

  return customFetch<AdminUserInfo>(getAdminUnbanUserUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}



export const getAccountLockoutAdminUnlockUrl = (id: string,) => {




  return `/admin/users/${id}/unlock`
}

export const accountLockoutAdminUnlock = async (id: string, options?: RequestInit): Promise<AccountLockoutMessageResponse> => {

  return customFetch<AccountLockoutMessageResponse>(getAccountLockoutAdminUnlockUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}



export const getApiKeysListUrl = () => {




  return `/api-keys`
}

export const apiKeysList = async ( options?: RequestInit): Promise<ApiKeyResponse[]> => {

  return customFetch<ApiKeyResponse[]>(getApiKeysListUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getApiKeysCreateUrl = () => {




  return `/api-keys`
}

export const apiKeysCreate = async (createApiKeyRequest: CreateApiKeyRequest, options?: RequestInit): Promise<CreateApiKeyResponse> => {

  return customFetch<CreateApiKeyResponse>(getApiKeysCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createApiKeyRequest,)
  }
);}



export const getApiKeysDeleteUrl = (id: string,) => {




  return `/api-keys/${id}`
}

export const apiKeysDelete = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getApiKeysDeleteUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}



export const getEmailPasswordChangePasswordUrl = () => {




  return `/change-password`
}

export const emailPasswordChangePassword = async (changePasswordRequest: ChangePasswordRequest, options?: RequestInit): Promise<MessageResponse> => {

  return customFetch<MessageResponse>(getEmailPasswordChangePasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      changePasswordRequest,)
  }
);}



export const getGetConfigUrl = () => {




  return `/config`
}

export const getConfig = async ( options?: RequestInit): Promise<AuthConfigResponse> => {

  return customFetch<AuthConfigResponse>(getGetConfigUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getEmailPasswordForgotPasswordUrl = () => {




  return `/forgot-password`
}

export const emailPasswordForgotPassword = async (forgotPasswordRequest: ForgotPasswordRequest, options?: RequestInit): Promise<MessageResponse> => {

  return customFetch<MessageResponse>(getEmailPasswordForgotPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      forgotPasswordRequest,)
  }
);}



export const getEmailPasswordLoginUrl = () => {




  return `/login`
}

export const emailPasswordLogin = async (loginRequest: LoginRequest, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getEmailPasswordLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginRequest,)
  }
);}



export const getLogoutUrl = () => {




  return `/logout`
}

export const logout = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



export const getMagicLinkSendUrl = () => {




  return `/magic-link/send`
}

export const magicLinkSend = async (magicLinkSendRequest: MagicLinkSendRequest, options?: RequestInit): Promise<MagicLinkMessageResponse> => {

  return customFetch<MagicLinkMessageResponse>(getMagicLinkSendUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      magicLinkSendRequest,)
  }
);}



export const getMagicLinkVerifyUrl = () => {




  return `/magic-link/verify`
}

export const magicLinkVerify = async (magicLinkVerifyRequest: MagicLinkVerifyRequest, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getMagicLinkVerifyUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      magicLinkVerifyRequest,)
  }
);}



export const getUpdateProfileUrl = () => {




  return `/me`
}

export const updateProfile = async (updateProfileRequest: UpdateProfileRequest, options?: RequestInit): Promise<AuthUser> => {

  return customFetch<AuthUser>(getUpdateProfileUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProfileRequest,)
  }
);}



export const getMfaGetBackupCodeCountUrl = () => {




  return `/mfa/backup-codes`
}

export const mfaGetBackupCodeCount = async ( options?: RequestInit): Promise<BackupCodeCountResponse> => {

  return customFetch<BackupCodeCountResponse>(getMfaGetBackupCodeCountUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getMfaRegenerateBackupCodesUrl = () => {




  return `/mfa/backup-codes/regenerate`
}

export const mfaRegenerateBackupCodes = async ( options?: RequestInit): Promise<BackupCodesResponse> => {

  return customFetch<BackupCodesResponse>(getMfaRegenerateBackupCodesUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



export const getMfaDisableUrl = () => {




  return `/mfa/totp`
}

export const mfaDisable = async ( options?: RequestInit): Promise<MfaMessageResponse> => {

  return customFetch<MfaMessageResponse>(getMfaDisableUrl(),
  {
    ...options,
    method: 'DELETE'


  }
);}



export const getMfaConfirmUrl = () => {




  return `/mfa/totp/confirm`
}

export const mfaConfirm = async (confirmTotpRequest: ConfirmTotpRequest, options?: RequestInit): Promise<MfaMessageResponse> => {

  return customFetch<MfaMessageResponse>(getMfaConfirmUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      confirmTotpRequest,)
  }
);}



export const getMfaSetupUrl = () => {




  return `/mfa/totp/setup`
}

export const mfaSetup = async ( options?: RequestInit): Promise<SetupTotpResponse> => {

  return customFetch<SetupTotpResponse>(getMfaSetupUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



export const getMfaVerifyUrl = () => {




  return `/mfa/verify`
}

export const mfaVerify = async (verifyMfaRequest: VerifyMfaRequest, options?: RequestInit): Promise<MfaAuthResponse> => {

  return customFetch<MfaAuthResponse>(getMfaVerifyUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      verifyMfaRequest,)
  }
);}



export const getOauthAccountsUrl = () => {




  return `/oauth/accounts`
}

export const oauthAccounts = async ( options?: RequestInit): Promise<OAuthAccountResponse[]> => {

  return customFetch<OAuthAccountResponse[]>(getOauthAccountsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getOauth2ServerAuthorizeUrl = () => {




  return `/oauth/authorize`
}

export const oauth2ServerAuthorize = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOauth2ServerAuthorizeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getOauth2ServerAuthorizeConsentUrl = () => {




  return `/oauth/authorize`
}

export const oauth2ServerAuthorizeConsent = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOauth2ServerAuthorizeConsentUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



export const getOauth2ServerDeviceVerifyUrl = () => {




  return `/oauth/device`
}

export const oauth2ServerDeviceVerify = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOauth2ServerDeviceVerifyUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getOauth2ServerDeviceApproveUrl = () => {




  return `/oauth/device`
}

export const oauth2ServerDeviceApprove = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOauth2ServerDeviceApproveUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



export const getOauth2ServerDeviceAuthorizeUrl = () => {




  return `/oauth/device/code`
}

export const oauth2ServerDeviceAuthorize = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOauth2ServerDeviceAuthorizeUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



export const getOauth2ServerIntrospectUrl = () => {




  return `/oauth/introspect`
}

export const oauth2ServerIntrospect = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOauth2ServerIntrospectUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



export const getOauth2ServerRegisterUrl = () => {




  return `/oauth/register`
}

export const oauth2ServerRegister = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOauth2ServerRegisterUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



export const getOauth2ServerRevokeUrl = () => {




  return `/oauth/revoke`
}

export const oauth2ServerRevoke = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOauth2ServerRevokeUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



export const getOauth2ServerTokenUrl = () => {




  return `/oauth/token`
}

export const oauth2ServerToken = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOauth2ServerTokenUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



export const getOauthUnlinkUrl = (provider: string,) => {




  return `/oauth/${provider}`
}

export const oauthUnlink = async (provider: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOauthUnlinkUrl(provider),
  {
    ...options,
    method: 'DELETE'


  }
);}



export const getOauthAuthorizeUrl = (provider: string,) => {




  return `/oauth/${provider}/authorize`
}

export const oauthAuthorize = async (provider: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOauthAuthorizeUrl(provider),
  {
    ...options,
    method: 'GET'


  }
);}



export const getOauthCallbackUrl = (provider: string,) => {




  return `/oauth/${provider}/callback`
}

export const oauthCallback = async (provider: string,
    callbackBody: CallbackBody, options?: RequestInit): Promise<OAuthAuthResponse> => {

  return customFetch<OAuthAuthResponse>(getOauthCallbackUrl(provider),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      callbackBody,)
  }
);}



export const getOauthLinkUrl = (provider: string,) => {




  return `/oauth/${provider}/link`
}

export const oauthLink = async (provider: string, options?: RequestInit): Promise<AuthorizeResponse> => {

  return customFetch<AuthorizeResponse>(getOauthLinkUrl(provider),
  {
    ...options,
    method: 'POST'


  }
);}



export const getPasskeyLoginBeginUrl = () => {




  return `/passkey/login/begin`
}

export const passkeyLoginBegin = async (passkeyLoginBeginRequest: PasskeyLoginBeginRequest, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getPasskeyLoginBeginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      passkeyLoginBeginRequest,)
  }
);}



export const getPasskeyLoginFinishUrl = () => {




  return `/passkey/login/finish`
}

export const passkeyLoginFinish = async (passkeyLoginFinishRequest: PasskeyLoginFinishRequest, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getPasskeyLoginFinishUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      passkeyLoginFinishRequest,)
  }
);}



export const getPasskeyListUrl = () => {




  return `/passkeys`
}

export const passkeyList = async ( options?: RequestInit): Promise<PasskeyInfo[]> => {

  return customFetch<PasskeyInfo[]>(getPasskeyListUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getPasskeyRegisterBeginUrl = () => {




  return `/passkeys/register/begin`
}

export const passkeyRegisterBegin = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getPasskeyRegisterBeginUrl(),
  {
    ...options,
    method: 'POST'


  }
);}



export const getPasskeyRegisterFinishUrl = () => {




  return `/passkeys/register/finish`
}

export const passkeyRegisterFinish = async (registerFinishRequest: RegisterFinishRequest, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getPasskeyRegisterFinishUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerFinishRequest,)
  }
);}



export const getPasskeyDeleteUrl = (id: string,) => {




  return `/passkeys/${id}`
}

export const passkeyDelete = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getPasskeyDeleteUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}



export const getEmailPasswordRegisterUrl = () => {




  return `/register`
}

export const emailPasswordRegister = async (registerRequest: RegisterRequest, options?: RequestInit): Promise<MessageResponse> => {

  return customFetch<MessageResponse>(getEmailPasswordRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerRequest,)
  }
);}



export const getEmailPasswordResendVerificationUrl = () => {




  return `/resend-verification`
}

export const emailPasswordResendVerification = async (resendVerificationRequest: ResendVerificationRequest, options?: RequestInit): Promise<MessageResponse> => {

  return customFetch<MessageResponse>(getEmailPasswordResendVerificationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      resendVerificationRequest,)
  }
);}



export const getEmailPasswordResetPasswordUrl = () => {




  return `/reset-password`
}

export const emailPasswordResetPassword = async (resetPasswordRequest: ResetPasswordRequest, options?: RequestInit): Promise<MessageResponse> => {

  return customFetch<MessageResponse>(getEmailPasswordResetPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      resetPasswordRequest,)
  }
);}



export const getGetSessionUrl = () => {




  return `/session`
}

export const getSession = async ( options?: RequestInit): Promise<AuthUser> => {

  return customFetch<AuthUser>(getGetSessionUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getBearerGetTokenUrl = () => {




  return `/token`
}

export const bearerGetToken = async (tokenRequest: TokenRequest, options?: RequestInit): Promise<TokenResponse> => {

  return customFetch<TokenResponse>(getBearerGetTokenUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      tokenRequest,)
  }
);}



export const getBearerRefreshUrl = () => {




  return `/token/refresh`
}

export const bearerRefresh = async (refreshRequest: RefreshRequest, options?: RequestInit): Promise<TokenResponse> => {

  return customFetch<TokenResponse>(getBearerRefreshUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      refreshRequest,)
  }
);}



export const getBearerRevokeUrl = () => {




  return `/token/revoke`
}

export const bearerRevoke = async (revokeRequest: RevokeRequest, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getBearerRevokeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      revokeRequest,)
  }
);}



export const getOidcUserinfoUrl = () => {




  return `/userinfo`
}

export const oidcUserinfo = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getOidcUserinfoUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getEmailPasswordVerifyEmailUrl = () => {




  return `/verify-email`
}

export const emailPasswordVerifyEmail = async (verifyEmailRequest: VerifyEmailRequest, options?: RequestInit): Promise<MessageResponse> => {

  return customFetch<MessageResponse>(getEmailPasswordVerifyEmailUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      verifyEmailRequest,)
  }
);}



export const getWebhooksListUrl = () => {




  return `/webhooks`
}

export const webhooksList = async ( options?: RequestInit): Promise<WebhookResponse[]> => {

  return customFetch<WebhookResponse[]>(getWebhooksListUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getWebhooksCreateUrl = () => {




  return `/webhooks`
}

export const webhooksCreate = async (createWebhookRequest: CreateWebhookRequest, options?: RequestInit): Promise<WebhookResponse> => {

  return customFetch<WebhookResponse>(getWebhooksCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createWebhookRequest,)
  }
);}



export const getWebhooksGetUrl = (id: string,) => {




  return `/webhooks/${id}`
}

export const webhooksGet = async (id: string, options?: RequestInit): Promise<WebhookDetailResponse> => {

  return customFetch<WebhookDetailResponse>(getWebhooksGetUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export const getWebhooksUpdateUrl = (id: string,) => {




  return `/webhooks/${id}`
}

export const webhooksUpdate = async (id: string,
    updateWebhookRequest: UpdateWebhookRequest, options?: RequestInit): Promise<WebhookResponse> => {

  return customFetch<WebhookResponse>(getWebhooksUpdateUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateWebhookRequest,)
  }
);}



export const getWebhooksDeleteUrl = (id: string,) => {




  return `/webhooks/${id}`
}

export const webhooksDelete = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getWebhooksDeleteUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}



export const getWebhooksTestUrl = (id: string,) => {




  return `/webhooks/${id}/test`
}

export const webhooksTest = async (id: string, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getWebhooksTestUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}
