-- Generated by cargo-yauth
-- Registered user accounts.
CREATE TABLE IF NOT EXISTS yauth_users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    display_name TEXT,
    email_verified INTEGER NOT NULL DEFAULT false,
    role TEXT NOT NULL DEFAULT 'user',
    banned INTEGER NOT NULL DEFAULT false,
    banned_reason TEXT,
    banned_until TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Ephemeral challenge storage for CSRF, WebAuthn, and MFA flows.
CREATE TABLE IF NOT EXISTS yauth_challenges (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    expires_at TEXT NOT NULL
);

-- Per-operation rate limit counters.
CREATE TABLE IF NOT EXISTS yauth_rate_limits (
    key TEXT PRIMARY KEY,
    count INTEGER NOT NULL DEFAULT 1,
    window_start TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Revoked JWT token IDs (JTI). TTL-based expiration.
CREATE TABLE IF NOT EXISTS yauth_revocations (
    key TEXT PRIMARY KEY,
    expires_at TEXT NOT NULL
);

-- OAuth CSRF state tokens. Consumed on callback.
CREATE TABLE IF NOT EXISTS yauth_oauth_states (
    state TEXT PRIMARY KEY,
    provider TEXT NOT NULL,
    redirect_url TEXT,
    expires_at TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Passwordless login tokens. Single-use, time-limited.
CREATE TABLE IF NOT EXISTS yauth_magic_links (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TEXT NOT NULL,
    used INTEGER NOT NULL DEFAULT false,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Registered OAuth2 server clients.
CREATE TABLE IF NOT EXISTS yauth_oauth2_clients (
    id TEXT PRIMARY KEY,
    client_id TEXT NOT NULL UNIQUE,
    client_secret_hash TEXT,
    redirect_uris TEXT NOT NULL,
    client_name TEXT,
    grant_types TEXT NOT NULL,
    scopes TEXT,
    is_public INTEGER NOT NULL DEFAULT false,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Webhook endpoint configurations.
CREATE TABLE IF NOT EXISTS yauth_webhooks (
    id TEXT PRIMARY KEY,
    url TEXT NOT NULL,
    secret TEXT NOT NULL,
    events TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT true,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- OIDC nonce values for replay protection.
CREATE TABLE IF NOT EXISTS yauth_oidc_nonces (
    id TEXT PRIMARY KEY,
    nonce_hash TEXT NOT NULL UNIQUE,
    authorization_code_id TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Active user sessions. One row per login.
CREATE TABLE IF NOT EXISTS yauth_sessions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES yauth_users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    ip_address TEXT,
    user_agent TEXT,
    expires_at TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Append-only authentication event log.
CREATE TABLE IF NOT EXISTS yauth_audit_log (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES yauth_users(id) ON DELETE SET NULL,
    event_type TEXT NOT NULL,
    metadata TEXT,
    ip_address TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Hashed passwords. One row per user.
CREATE TABLE IF NOT EXISTS yauth_passwords (
    user_id TEXT PRIMARY KEY REFERENCES yauth_users(id) ON DELETE CASCADE,
    password_hash TEXT NOT NULL
);

-- Pending email verification tokens.
CREATE TABLE IF NOT EXISTS yauth_email_verifications (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES yauth_users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Pending password reset tokens.
CREATE TABLE IF NOT EXISTS yauth_password_resets (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES yauth_users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TEXT NOT NULL,
    used_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- WebAuthn/passkey credentials. Multiple per user.
CREATE TABLE IF NOT EXISTS yauth_webauthn_credentials (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES yauth_users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    aaguid TEXT,
    device_name TEXT,
    credential TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TEXT
);

-- TOTP secrets for MFA. One per user.
CREATE TABLE IF NOT EXISTS yauth_totp_secrets (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES yauth_users(id) ON DELETE CASCADE UNIQUE,
    encrypted_secret TEXT NOT NULL,
    verified INTEGER NOT NULL DEFAULT false,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- MFA backup codes. Multiple per user, single-use.
CREATE TABLE IF NOT EXISTS yauth_backup_codes (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES yauth_users(id) ON DELETE CASCADE,
    code_hash TEXT NOT NULL,
    used INTEGER NOT NULL DEFAULT false,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Linked OAuth provider accounts.
CREATE TABLE IF NOT EXISTS yauth_oauth_accounts (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES yauth_users(id) ON DELETE CASCADE,
    provider TEXT NOT NULL,
    provider_user_id TEXT NOT NULL,
    access_token_enc TEXT,
    refresh_token_enc TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TEXT,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- JWT refresh tokens with rotation family tracking.
CREATE TABLE IF NOT EXISTS yauth_refresh_tokens (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES yauth_users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    family_id TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    revoked INTEGER NOT NULL DEFAULT false,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- API keys. Identified by prefix, verified by hash.
CREATE TABLE IF NOT EXISTS yauth_api_keys (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES yauth_users(id) ON DELETE CASCADE,
    key_prefix TEXT NOT NULL UNIQUE,
    key_hash TEXT NOT NULL,
    name TEXT NOT NULL,
    scopes TEXT,
    last_used_at TEXT,
    expires_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- OAuth2 authorization codes. Single-use, time-limited.
CREATE TABLE IF NOT EXISTS yauth_authorization_codes (
    id TEXT PRIMARY KEY,
    code_hash TEXT NOT NULL UNIQUE,
    client_id TEXT NOT NULL,
    user_id TEXT REFERENCES yauth_users(id) ON DELETE CASCADE,
    scopes TEXT,
    redirect_uri TEXT NOT NULL,
    code_challenge TEXT NOT NULL,
    code_challenge_method TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    used INTEGER NOT NULL DEFAULT false,
    nonce TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- User consent records for OAuth2 clients.
CREATE TABLE IF NOT EXISTS yauth_consents (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES yauth_users(id) ON DELETE CASCADE,
    client_id TEXT NOT NULL,
    scopes TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Device authorization flow codes.
CREATE TABLE IF NOT EXISTS yauth_device_codes (
    id TEXT PRIMARY KEY,
    device_code_hash TEXT NOT NULL UNIQUE,
    user_code TEXT NOT NULL UNIQUE,
    client_id TEXT NOT NULL,
    scopes TEXT,
    user_id TEXT REFERENCES yauth_users(id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'pending',
    interval INTEGER NOT NULL DEFAULT 5,
    expires_at TEXT NOT NULL,
    last_polled_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Account lockout state. One row per user.
CREATE TABLE IF NOT EXISTS yauth_account_locks (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES yauth_users(id) ON DELETE CASCADE UNIQUE,
    failed_count INTEGER NOT NULL DEFAULT 0,
    locked_until TEXT,
    lock_count INTEGER NOT NULL DEFAULT 0,
    locked_reason TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Account unlock tokens. Time-limited.
CREATE TABLE IF NOT EXISTS yauth_unlock_tokens (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES yauth_users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Webhook delivery attempts and responses.
CREATE TABLE IF NOT EXISTS yauth_webhook_deliveries (
    id TEXT PRIMARY KEY,
    webhook_id TEXT REFERENCES yauth_webhooks(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    payload TEXT NOT NULL,
    status_code INTEGER,
    response_body TEXT,
    success INTEGER NOT NULL DEFAULT false,
    attempt INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

