//! Diesel `table!` macro code generator.
//!
//! Generates valid Rust source text (as a `String`) containing `diesel::table!`
//! macro invocations for each table in the schema. This is **string-based code
//! generation** -- the crate has zero diesel dependencies.

use crate::collector::YAuthSchema;
use crate::types::{ColumnType, Dialect, TableDef};

/// Map abstract column type to a diesel type name for the given dialect.
fn diesel_type(col_type: &ColumnType, nullable: bool, dialect: Dialect) -> String {
    let base = match dialect {
        Dialect::Postgres => match col_type {
            ColumnType::Uuid => "Uuid",
            ColumnType::Varchar | ColumnType::VarcharN(_) => "Varchar",
            ColumnType::Boolean => "Bool",
            ColumnType::DateTime => "Timestamptz",
            ColumnType::Json => "Jsonb",
            ColumnType::Int => "Int4",
            ColumnType::SmallInt => "Int2",
            ColumnType::Text => "Text",
        },
        Dialect::Sqlite => match col_type {
            ColumnType::Uuid
            | ColumnType::Varchar
            | ColumnType::VarcharN(_)
            | ColumnType::DateTime
            | ColumnType::Json
            | ColumnType::Text => "Text",
            ColumnType::Boolean => "Bool",
            ColumnType::Int => "Integer",
            ColumnType::SmallInt => "SmallInt",
        },
        Dialect::Mysql => match col_type {
            ColumnType::Uuid
            | ColumnType::Varchar
            | ColumnType::VarcharN(_)
            | ColumnType::Json
            | ColumnType::Text => "Text",
            ColumnType::Boolean => "Bool",
            ColumnType::DateTime => "Datetime",
            ColumnType::Int => "Integer",
            ColumnType::SmallInt => "SmallInt",
        },
    };

    if nullable {
        format!("Nullable<{base}>")
    } else {
        base.to_string()
    }
}

/// Find the primary key column name for a table.
/// Falls back to `"id"` if no explicit PK column is found.
fn primary_key_column(table: &TableDef) -> &str {
    table
        .columns
        .iter()
        .find(|c| c.primary_key)
        .map(|c| c.name.as_str())
        .unwrap_or("id")
}

/// Generate a single `diesel::table! { ... }` block for one table.
fn generate_table_macro(table: &TableDef, dialect: Dialect) -> String {
    let pk = primary_key_column(table);
    let mut out = format!("diesel::table! {{\n    {} ({}) {{\n", table.name, pk);

    for col in &table.columns {
        let dtype = diesel_type(&col.col_type, col.nullable, dialect);
        out.push_str(&format!("        {} -> {},\n", col.name, dtype));
    }

    out.push_str("    }\n}\n");
    out
}

/// Collect foreign key joinable! declarations for all tables in the schema.
fn generate_joinables(schema: &YAuthSchema) -> String {
    let mut out = String::new();

    for table in &schema.tables {
        for col in &table.columns {
            if let Some(ref fk) = col.foreign_key {
                // Only generate joinable if the FK column name differs from the
                // referenced table's PK (diesel requires this for unambiguous joins).
                // Also skip self-referential FKs.
                if fk.references_table != table.name {
                    out.push_str(&format!(
                        "diesel::joinable!({} -> {} ({}));\n",
                        table.name, fk.references_table, col.name
                    ));
                }
            }
        }
    }

    out
}

/// Generate diesel `table!` macro definitions as Rust source text.
///
/// The output is a complete, valid Rust file containing `diesel::table!` blocks
/// for every table in the schema, followed by `diesel::joinable!` declarations
/// for foreign key relationships.
pub fn generate_diesel_schema(schema: &YAuthSchema, dialect: Dialect) -> String {
    let mut out = String::from(
        "// @generated by cargo-yauth -- DO NOT EDIT\n\
         // Dialect: ",
    );
    out.push_str(&dialect.to_string());
    out.push('\n');
    out.push('\n');

    for (i, table) in schema.tables.iter().enumerate() {
        if i > 0 {
            out.push('\n');
        }
        out.push_str(&generate_table_macro(table, dialect));
    }

    // Joinable declarations
    let joinables = generate_joinables(schema);
    if !joinables.is_empty() {
        out.push('\n');
        out.push_str(&joinables);
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{collect_schema, collect_schema_for_plugins, core_schema, plugin_schemas};

    #[test]
    fn postgres_core_schema_matches_hand_written() {
        let schema = collect_schema(vec![core_schema()]).unwrap();
        let output = generate_diesel_schema(&schema, Dialect::Postgres);

        // Verify table! blocks exist
        assert!(output.contains("diesel::table! {\n    yauth_users (id) {"));
        assert!(output.contains("diesel::table! {\n    yauth_sessions (id) {"));
        assert!(output.contains("diesel::table! {\n    yauth_audit_log (id) {"));

        // Verify PG-specific types
        assert!(output.contains("id -> Uuid,"));
        assert!(output.contains("email -> Varchar,"));
        assert!(output.contains("email_verified -> Bool,"));
        assert!(output.contains("created_at -> Timestamptz,"));
        assert!(output.contains("display_name -> Nullable<Varchar>,"));

        // Verify joinable
        assert!(output.contains("diesel::joinable!(yauth_sessions -> yauth_users (user_id));"));
    }

    #[test]
    fn sqlite_core_schema_types() {
        let schema = collect_schema(vec![core_schema()]).unwrap();
        let output = generate_diesel_schema(&schema, Dialect::Sqlite);

        assert!(output.contains("id -> Text,"));
        assert!(output.contains("email -> Text,"));
        assert!(output.contains("email_verified -> Bool,"));
        assert!(output.contains("created_at -> Text,"));
        assert!(output.contains("display_name -> Nullable<Text>,"));
        // No Postgres types
        assert!(!output.contains("Uuid"));
        assert!(!output.contains("Timestamptz"));
        assert!(!output.contains("Jsonb"));
    }

    #[test]
    fn mysql_core_schema_types() {
        let schema = collect_schema(vec![core_schema()]).unwrap();
        let output = generate_diesel_schema(&schema, Dialect::Mysql);

        assert!(output.contains("id -> Text,"));
        assert!(output.contains("email_verified -> Bool,"));
        assert!(output.contains("created_at -> Datetime,"));
        assert!(output.contains("metadata -> Nullable<Text>,"));
        // No Postgres types
        assert!(!output.contains("Uuid"));
        assert!(!output.contains("Timestamptz"));
        assert!(!output.contains("Jsonb"));
    }

    #[test]
    fn full_schema_all_dialects() {
        let schema = collect_schema(vec![
            core_schema(),
            plugin_schemas::email_password_schema(),
            plugin_schemas::passkey_schema(),
            plugin_schemas::mfa_schema(),
            plugin_schemas::oauth_schema(),
            plugin_schemas::bearer_schema(),
            plugin_schemas::api_key_schema(),
        ])
        .unwrap();

        for dialect in [Dialect::Postgres, Dialect::Sqlite, Dialect::Mysql] {
            let output = generate_diesel_schema(&schema, dialect);
            // Every table should have a table! block
            for table in &schema.tables {
                assert!(
                    output.contains(&format!("diesel::table! {{\n    {} (", table.name)),
                    "Missing table! for {} in {:?} dialect",
                    table.name,
                    dialect
                );
            }
        }
    }

    #[test]
    fn custom_prefix_in_generated_schema() {
        let schema = collect_schema_for_plugins(&["email-password".to_string()], "auth_").unwrap();
        let output = generate_diesel_schema(&schema, Dialect::Postgres);

        assert!(output.contains("auth_users (id)"));
        assert!(output.contains("auth_passwords (user_id)"));
        assert!(!output.contains("yauth_"));
        assert!(output.contains("diesel::joinable!(auth_passwords -> auth_users (user_id));"));
    }

    #[test]
    fn postgres_json_maps_to_jsonb() {
        let schema = collect_schema(vec![core_schema()]).unwrap();
        let output = generate_diesel_schema(&schema, Dialect::Postgres);
        // audit_log.metadata is Json -> Jsonb in PG
        assert!(output.contains("metadata -> Nullable<Jsonb>,"));
    }

    #[test]
    fn postgres_int_maps_to_int4() {
        let schema =
            collect_schema(vec![core_schema(), plugin_schemas::oauth2_server_schema()]).unwrap();
        let output = generate_diesel_schema(&schema, Dialect::Postgres);
        // device_codes.interval is Int -> Int4
        assert!(output.contains("interval -> Int4,"));
    }

    #[test]
    fn postgres_smallint_maps_to_int2() {
        let schema =
            collect_schema(vec![core_schema(), plugin_schemas::webhooks_schema()]).unwrap();
        let output = generate_diesel_schema(&schema, Dialect::Postgres);
        // webhook_deliveries.status_code is SmallInt -> Nullable<Int2>
        assert!(output.contains("status_code -> Nullable<Int2>,"));
    }

    #[test]
    fn sqlite_int_maps_to_integer() {
        let schema = collect_schema(vec![
            core_schema(),
            plugin_schemas::account_lockout_schema(),
        ])
        .unwrap();
        let output = generate_diesel_schema(&schema, Dialect::Sqlite);
        assert!(output.contains("failed_count -> Integer,"));
    }

    #[test]
    fn generated_header_includes_dialect() {
        let schema = collect_schema(vec![core_schema()]).unwrap();
        for dialect in [Dialect::Postgres, Dialect::Sqlite, Dialect::Mysql] {
            let output = generate_diesel_schema(&schema, dialect);
            assert!(output.starts_with("// @generated by cargo-yauth -- DO NOT EDIT\n"));
            assert!(output.contains(&format!("// Dialect: {}", dialect)));
        }
    }

    #[test]
    fn primary_key_column_detected() {
        // yauth_passwords has user_id as PK, not id
        let schema =
            collect_schema(vec![core_schema(), plugin_schemas::email_password_schema()]).unwrap();
        let output = generate_diesel_schema(&schema, Dialect::Postgres);
        assert!(output.contains("yauth_passwords (user_id)"));
    }
}
