//! Toasty model code generator.
//!
//! Generates valid Rust source text containing `#[derive(toasty::Model)]`
//! struct definitions for each table in the schema. This is **string-based
//! code generation** -- the crate has zero toasty dependencies.

use crate::collector::YAuthSchema;
use crate::types::{ColumnDef, ColumnType, TableDef};

/// Map abstract column type to a Toasty Rust type for the model struct field.
/// Toasty stores datetimes and JSON as strings; UUIDs use `uuid::Uuid`.
fn rust_type(col: &ColumnDef) -> String {
    let base = match col.col_type {
        ColumnType::Uuid => "uuid::Uuid",
        ColumnType::Varchar | ColumnType::VarcharN(_) | ColumnType::Text => "String",
        ColumnType::Boolean => "bool",
        ColumnType::DateTime => "String", // Toasty lacks chrono support; store as ISO 8601
        ColumnType::Json => "String",     // Toasty lacks native JSON; store as serialized string
        ColumnType::Int => "i64",         // Toasty uses i64 for integers
        ColumnType::SmallInt => "i64",
    };
    if col.nullable {
        format!("Option<{base}>")
    } else {
        base.to_string()
    }
}

/// Convert a table name like `yauth_users` to a PascalCase model name like `YauthUser`.
/// Strips the prefix, singularizes naively, and converts to PascalCase.
fn model_name(table_name: &str) -> String {
    table_name
        .split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// Convert a table name to the `#[table = "..."]` value (without prefix).
fn table_attr(table_name: &str, prefix: &str) -> String {
    table_name
        .strip_prefix(prefix)
        .unwrap_or(table_name)
        .to_string()
}

/// Generate a single Toasty model struct for one table.
fn generate_model(table: &TableDef, prefix: &str) -> String {
    let name = model_name(&table.name);
    let table_val = table_attr(&table.name, prefix);
    let mut out = String::new();

    out.push_str(&format!("/// Toasty model for `{}`.\n", table.name));
    out.push_str("#[derive(Debug, toasty::Model)]\n");
    out.push_str(&format!("#[table = \"{}\"]\n", table_val));
    out.push_str(&format!("pub struct {} {{\n", name));

    for col in &table.columns {
        // Key attribute
        if col.primary_key {
            out.push_str("    #[key]\n");
            if col.col_type == ColumnType::Uuid {
                out.push_str("    #[auto]\n");
            }
        }

        // Unique attribute
        if col.unique && !col.primary_key {
            out.push_str("    #[unique]\n");
        }

        // BelongsTo relationship
        if let Some(fk) = col
            .foreign_key
            .as_ref()
            .filter(|fk| fk.references_table != table.name)
        {
            out.push_str(&format!(
                "    #[belongs_to(key = {}, references = {})]\n",
                col.name, fk.references_column
            ));
        }

        let rust_ty = rust_type(col);
        out.push_str(&format!("    pub {}: {},\n", col.name, rust_ty));
    }

    out.push_str("}\n");
    out
}

/// Generate the module file containing all Toasty models.
fn generate_models_mod(schema: &YAuthSchema, prefix: &str) -> String {
    let mut out = String::from("// @generated by cargo-yauth -- DO NOT EDIT\n");
    out.push_str("//\n");
    out.push_str("// Toasty model definitions for yauth tables.\n");
    out.push_str(&format!(
        "// Use with: Db::builder().table_name_prefix(\"{}\").models(toasty::models!(crate::*))\n\n",
        prefix
    ));

    for (i, table) in schema.tables.iter().enumerate() {
        if i > 0 {
            out.push('\n');
        }
        out.push_str(&generate_model(table, prefix));
    }

    out
}

/// Generate Toasty model files for all tables in the schema.
///
/// Returns a list of `(relative_path, content)` pairs.
/// Unlike SeaORM (one file per entity), Toasty models go in a single file
/// since they use inventory-based registration.
pub fn generate_toasty_models(schema: &YAuthSchema, prefix: &str) -> Vec<(String, String)> {
    vec![("models.rs".to_string(), generate_models_mod(schema, prefix))]
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{collect_schema, collect_schema_for_plugins, core_schema, plugin_schemas};

    #[test]
    fn generates_core_models() {
        let schema = collect_schema(vec![core_schema()]).unwrap();
        let files = generate_toasty_models(&schema, "yauth_");

        assert_eq!(files.len(), 1);
        let (name, content) = &files[0];
        assert_eq!(name, "models.rs");
        assert!(content.contains("#[derive(Debug, toasty::Model)]"));
        assert!(content.contains("#[table = \"users\"]"));
        assert!(content.contains("pub struct YauthUsers"));
        assert!(content.contains("pub id: uuid::Uuid"));
        assert!(content.contains("pub email: String"));
        assert!(content.contains("pub email_verified: bool"));
        assert!(content.contains("#[key]"));
        assert!(content.contains("#[auto]"));
    }

    #[test]
    fn generates_relationships() {
        let schema = collect_schema(vec![core_schema()]).unwrap();
        let files = generate_toasty_models(&schema, "yauth_");
        let content = &files[0].1;

        assert!(content.contains("#[belongs_to(key = user_id, references = id)]"));
    }

    #[test]
    fn generates_plugin_models() {
        let schema =
            collect_schema(vec![core_schema(), plugin_schemas::email_password_schema()]).unwrap();
        let files = generate_toasty_models(&schema, "yauth_");
        let content = &files[0].1;

        assert!(content.contains("#[table = \"passwords\"]"));
        assert!(content.contains("pub struct YauthPasswords"));
    }

    #[test]
    fn custom_prefix() {
        let schema = collect_schema_for_plugins(&["email-password".to_string()], "auth_").unwrap();
        let files = generate_toasty_models(&schema, "auth_");
        let content = &files[0].1;

        assert!(content.contains("#[table = \"users\"]"));
        assert!(content.contains("pub struct AuthUsers"));
        assert!(!content.contains("yauth_"));
    }

    #[test]
    fn json_columns_are_string() {
        let schema = collect_schema(vec![core_schema()]).unwrap();
        let files = generate_toasty_models(&schema, "yauth_");
        let content = &files[0].1;

        // audit_log.metadata is Json -> String in Toasty
        assert!(content.contains("pub metadata: Option<String>"));
    }

    #[test]
    fn datetime_columns_are_string() {
        let schema = collect_schema(vec![core_schema()]).unwrap();
        let files = generate_toasty_models(&schema, "yauth_");
        let content = &files[0].1;

        // created_at is DateTime -> String in Toasty
        assert!(content.contains("pub created_at: String"));
    }
}
