-- Generated by cargo-yauth
DROP TABLE IF EXISTS yauth_users CASCADE;

DROP TABLE IF EXISTS yauth_challenges CASCADE;

DROP TABLE IF EXISTS yauth_rate_limits CASCADE;

DROP TABLE IF EXISTS yauth_revocations CASCADE;

DROP TABLE IF EXISTS yauth_oauth_states CASCADE;

DROP TABLE IF EXISTS yauth_magic_links CASCADE;

DROP TABLE IF EXISTS yauth_oauth2_clients CASCADE;

DROP TABLE IF EXISTS yauth_webhooks CASCADE;

DROP TABLE IF EXISTS yauth_oidc_nonces CASCADE;

DROP TABLE IF EXISTS yauth_sessions CASCADE;

DROP TABLE IF EXISTS yauth_audit_log CASCADE;

DROP TABLE IF EXISTS yauth_passwords CASCADE;

DROP TABLE IF EXISTS yauth_email_verifications CASCADE;

DROP TABLE IF EXISTS yauth_password_resets CASCADE;

DROP TABLE IF EXISTS yauth_webauthn_credentials CASCADE;

DROP TABLE IF EXISTS yauth_totp_secrets CASCADE;

DROP TABLE IF EXISTS yauth_backup_codes CASCADE;

DROP TABLE IF EXISTS yauth_oauth_accounts CASCADE;

DROP TABLE IF EXISTS yauth_refresh_tokens CASCADE;

DROP TABLE IF EXISTS yauth_api_keys CASCADE;

DROP TABLE IF EXISTS yauth_authorization_codes CASCADE;

DROP TABLE IF EXISTS yauth_consents CASCADE;

DROP TABLE IF EXISTS yauth_device_codes CASCADE;

DROP TABLE IF EXISTS yauth_account_locks CASCADE;

DROP TABLE IF EXISTS yauth_unlock_tokens CASCADE;

DROP TABLE IF EXISTS yauth_webhook_deliveries CASCADE;

