// @generated by cargo-yauth -- DO NOT EDIT
//
// Toasty model definitions for yauth tables.
// Use with: Db::builder().table_name_prefix("yauth_").models(toasty::models!(crate::*))

/// Toasty model for `yauth_users`.
#[derive(Debug, toasty::Model)]
#[table = "users"]
pub struct YauthUsers {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[unique]
    pub email: String,
    pub display_name: Option<String>,
    pub email_verified: bool,
    pub role: String,
    pub banned: bool,
    pub banned_reason: Option<String>,
    pub banned_until: Option<String>,
    pub created_at: String,
    pub updated_at: String,
}

/// Toasty model for `yauth_challenges`.
#[derive(Debug, toasty::Model)]
#[table = "challenges"]
pub struct YauthChallenges {
    #[key]
    pub key: String,
    pub value: String,
    pub expires_at: String,
}

/// Toasty model for `yauth_rate_limits`.
#[derive(Debug, toasty::Model)]
#[table = "rate_limits"]
pub struct YauthRateLimits {
    #[key]
    pub key: String,
    pub count: i64,
    pub window_start: String,
}

/// Toasty model for `yauth_revocations`.
#[derive(Debug, toasty::Model)]
#[table = "revocations"]
pub struct YauthRevocations {
    #[key]
    pub key: String,
    pub expires_at: String,
}

/// Toasty model for `yauth_oauth_states`.
#[derive(Debug, toasty::Model)]
#[table = "oauth_states"]
pub struct YauthOauthStates {
    #[key]
    pub state: String,
    pub provider: String,
    pub redirect_url: Option<String>,
    pub expires_at: String,
    pub created_at: String,
}

/// Toasty model for `yauth_magic_links`.
#[derive(Debug, toasty::Model)]
#[table = "magic_links"]
pub struct YauthMagicLinks {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    pub email: String,
    #[unique]
    pub token_hash: String,
    pub expires_at: String,
    pub used: bool,
    pub created_at: String,
}

/// Toasty model for `yauth_oauth2_clients`.
#[derive(Debug, toasty::Model)]
#[table = "oauth2_clients"]
pub struct YauthOauth2Clients {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[unique]
    pub client_id: String,
    pub client_secret_hash: Option<String>,
    pub redirect_uris: String,
    pub client_name: Option<String>,
    pub grant_types: String,
    pub scopes: Option<String>,
    pub is_public: bool,
    pub created_at: String,
    pub token_endpoint_auth_method: Option<String>,
    pub public_key_pem: Option<String>,
    pub jwks_uri: Option<String>,
    pub banned_at: Option<String>,
    pub banned_reason: Option<String>,
}

/// Toasty model for `yauth_webhooks`.
#[derive(Debug, toasty::Model)]
#[table = "webhooks"]
pub struct YauthWebhooks {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    pub url: String,
    pub secret: String,
    pub events: String,
    pub active: bool,
    pub created_at: String,
    pub updated_at: String,
}

/// Toasty model for `yauth_oidc_nonces`.
#[derive(Debug, toasty::Model)]
#[table = "oidc_nonces"]
pub struct YauthOidcNonces {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[unique]
    pub nonce_hash: String,
    pub authorization_code_id: uuid::Uuid,
    pub created_at: String,
}

/// Toasty model for `yauth_sessions`.
#[derive(Debug, toasty::Model)]
#[table = "sessions"]
pub struct YauthSessions {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[belongs_to(key = user_id, references = id)]
    pub user_id: uuid::Uuid,
    #[unique]
    pub token_hash: String,
    pub ip_address: Option<String>,
    pub user_agent: Option<String>,
    pub expires_at: String,
    pub created_at: String,
}

/// Toasty model for `yauth_audit_log`.
#[derive(Debug, toasty::Model)]
#[table = "audit_log"]
pub struct YauthAuditLog {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[belongs_to(key = user_id, references = id)]
    pub user_id: Option<uuid::Uuid>,
    pub event_type: String,
    pub metadata: Option<String>,
    pub ip_address: Option<String>,
    pub created_at: String,
}

/// Toasty model for `yauth_passwords`.
#[derive(Debug, toasty::Model)]
#[table = "passwords"]
pub struct YauthPasswords {
    #[key]
    #[auto]
    #[belongs_to(key = user_id, references = id)]
    pub user_id: uuid::Uuid,
    pub password_hash: String,
}

/// Toasty model for `yauth_email_verifications`.
#[derive(Debug, toasty::Model)]
#[table = "email_verifications"]
pub struct YauthEmailVerifications {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[belongs_to(key = user_id, references = id)]
    pub user_id: Option<uuid::Uuid>,
    #[unique]
    pub token_hash: String,
    pub expires_at: String,
    pub created_at: String,
}

/// Toasty model for `yauth_password_resets`.
#[derive(Debug, toasty::Model)]
#[table = "password_resets"]
pub struct YauthPasswordResets {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[belongs_to(key = user_id, references = id)]
    pub user_id: Option<uuid::Uuid>,
    #[unique]
    pub token_hash: String,
    pub expires_at: String,
    pub used_at: Option<String>,
    pub created_at: String,
}

/// Toasty model for `yauth_webauthn_credentials`.
#[derive(Debug, toasty::Model)]
#[table = "webauthn_credentials"]
pub struct YauthWebauthnCredentials {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[belongs_to(key = user_id, references = id)]
    pub user_id: Option<uuid::Uuid>,
    pub name: String,
    pub aaguid: Option<String>,
    pub device_name: Option<String>,
    pub credential: String,
    pub created_at: String,
    pub last_used_at: Option<String>,
}

/// Toasty model for `yauth_totp_secrets`.
#[derive(Debug, toasty::Model)]
#[table = "totp_secrets"]
pub struct YauthTotpSecrets {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[unique]
    #[belongs_to(key = user_id, references = id)]
    pub user_id: Option<uuid::Uuid>,
    pub encrypted_secret: String,
    pub verified: bool,
    pub created_at: String,
}

/// Toasty model for `yauth_backup_codes`.
#[derive(Debug, toasty::Model)]
#[table = "backup_codes"]
pub struct YauthBackupCodes {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[belongs_to(key = user_id, references = id)]
    pub user_id: Option<uuid::Uuid>,
    pub code_hash: String,
    pub used: bool,
    pub created_at: String,
}

/// Toasty model for `yauth_oauth_accounts`.
#[derive(Debug, toasty::Model)]
#[table = "oauth_accounts"]
pub struct YauthOauthAccounts {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[belongs_to(key = user_id, references = id)]
    pub user_id: Option<uuid::Uuid>,
    pub provider: String,
    pub provider_user_id: String,
    pub access_token_enc: Option<String>,
    pub refresh_token_enc: Option<String>,
    pub created_at: String,
    pub expires_at: Option<String>,
    pub updated_at: String,
}

/// Toasty model for `yauth_refresh_tokens`.
#[derive(Debug, toasty::Model)]
#[table = "refresh_tokens"]
pub struct YauthRefreshTokens {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[belongs_to(key = user_id, references = id)]
    pub user_id: Option<uuid::Uuid>,
    #[unique]
    pub token_hash: String,
    pub family_id: uuid::Uuid,
    pub expires_at: String,
    pub revoked: bool,
    pub created_at: String,
}

/// Toasty model for `yauth_api_keys`.
#[derive(Debug, toasty::Model)]
#[table = "api_keys"]
pub struct YauthApiKeys {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[belongs_to(key = user_id, references = id)]
    pub user_id: Option<uuid::Uuid>,
    #[unique]
    pub key_prefix: String,
    pub key_hash: String,
    pub name: String,
    pub scopes: Option<String>,
    pub last_used_at: Option<String>,
    pub expires_at: Option<String>,
    pub created_at: String,
}

/// Toasty model for `yauth_authorization_codes`.
#[derive(Debug, toasty::Model)]
#[table = "authorization_codes"]
pub struct YauthAuthorizationCodes {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[unique]
    pub code_hash: String,
    pub client_id: String,
    #[belongs_to(key = user_id, references = id)]
    pub user_id: Option<uuid::Uuid>,
    pub scopes: Option<String>,
    pub redirect_uri: String,
    pub code_challenge: String,
    pub code_challenge_method: String,
    pub expires_at: String,
    pub used: bool,
    pub nonce: Option<String>,
    pub created_at: String,
}

/// Toasty model for `yauth_consents`.
#[derive(Debug, toasty::Model)]
#[table = "consents"]
pub struct YauthConsents {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[belongs_to(key = user_id, references = id)]
    pub user_id: Option<uuid::Uuid>,
    pub client_id: String,
    pub scopes: Option<String>,
    pub created_at: String,
}

/// Toasty model for `yauth_device_codes`.
#[derive(Debug, toasty::Model)]
#[table = "device_codes"]
pub struct YauthDeviceCodes {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[unique]
    pub device_code_hash: String,
    #[unique]
    pub user_code: String,
    pub client_id: String,
    pub scopes: Option<String>,
    #[belongs_to(key = user_id, references = id)]
    pub user_id: Option<uuid::Uuid>,
    pub status: String,
    pub interval: i64,
    pub expires_at: String,
    pub last_polled_at: Option<String>,
    pub created_at: String,
}

/// Toasty model for `yauth_account_locks`.
#[derive(Debug, toasty::Model)]
#[table = "account_locks"]
pub struct YauthAccountLocks {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[unique]
    #[belongs_to(key = user_id, references = id)]
    pub user_id: Option<uuid::Uuid>,
    pub failed_count: i64,
    pub locked_until: Option<String>,
    pub lock_count: i64,
    pub locked_reason: Option<String>,
    pub created_at: String,
    pub updated_at: String,
}

/// Toasty model for `yauth_unlock_tokens`.
#[derive(Debug, toasty::Model)]
#[table = "unlock_tokens"]
pub struct YauthUnlockTokens {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[belongs_to(key = user_id, references = id)]
    pub user_id: Option<uuid::Uuid>,
    #[unique]
    pub token_hash: String,
    pub expires_at: String,
    pub created_at: String,
}

/// Toasty model for `yauth_webhook_deliveries`.
#[derive(Debug, toasty::Model)]
#[table = "webhook_deliveries"]
pub struct YauthWebhookDeliveries {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[belongs_to(key = webhook_id, references = id)]
    pub webhook_id: Option<uuid::Uuid>,
    pub event_type: String,
    pub payload: String,
    pub status_code: Option<i64>,
    pub response_body: Option<String>,
    pub success: bool,
    pub attempt: i64,
    pub created_at: String,
}
