// @generated by cargo-yauth -- DO NOT EDIT
//
// Toasty 0.4 model definitions for yauth tables.
//
// Usage:
//     let db = toasty::Db::builder()
//         .table_name_prefix("yauth_")
//         .models(toasty::models!(crate::*))
//         .connect("sqlite://yauth.db")
//         .await?;
//     // Production: apply the tracked migration chain (see Toasty.toml):
//     // yauth_toasty::apply_migrations(&db).await?;

/// Toasty model for `yauth_users`.
#[derive(Debug, toasty::Model)]
#[table = "users"]
pub struct YauthUser {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[unique]
    pub email: String,
    pub display_name: Option<String>,
    pub email_verified: bool,
    pub role: String,
    pub banned: bool,
    pub banned_reason: Option<String>,
    pub banned_until: Option<jiff::Timestamp>,
    pub created_at: jiff::Timestamp,
    pub updated_at: jiff::Timestamp,
    #[has_many]
    pub sessions: toasty::HasMany<YauthSession>,
    #[has_many]
    pub audit_logs: toasty::HasMany<YauthAuditLog>,
    #[has_one]
    pub password: toasty::HasOne<YauthPassword>,
    #[has_many]
    pub email_verifications: toasty::HasMany<YauthEmailVerification>,
    #[has_many]
    pub password_resets: toasty::HasMany<YauthPasswordReset>,
    #[has_many]
    pub webauthn_credentials: toasty::HasMany<YauthWebauthnCredential>,
    #[has_one]
    pub totp_secret: toasty::HasOne<YauthTotpSecret>,
    #[has_many]
    pub backup_codes: toasty::HasMany<YauthBackupCode>,
    #[has_many]
    pub oauth_accounts: toasty::HasMany<YauthOauthAccount>,
    #[has_many]
    pub refresh_tokens: toasty::HasMany<YauthRefreshToken>,
    #[has_many]
    pub api_keys: toasty::HasMany<YauthApiKey>,
    #[has_many]
    pub authorization_codes: toasty::HasMany<YauthAuthorizationCode>,
    #[has_many]
    pub consents: toasty::HasMany<YauthConsent>,
    #[has_many]
    pub device_codes: toasty::HasMany<YauthDeviceCode>,
    #[has_one]
    pub account_lock: toasty::HasOne<YauthAccountLock>,
    #[has_many]
    pub unlock_tokens: toasty::HasMany<YauthUnlockToken>,
}

/// Toasty model for `yauth_challenges`.
#[derive(Debug, toasty::Model)]
#[table = "challenges"]
pub struct YauthChallenge {
    #[key]
    pub key: String,
    #[serialize(json)]
    pub value: serde_json::Value,
    pub expires_at: jiff::Timestamp,
}

/// Toasty model for `yauth_rate_limits`.
#[derive(Debug, toasty::Model)]
#[table = "rate_limits"]
pub struct YauthRateLimit {
    #[key]
    pub key: String,
    pub count: i64,
    pub window_start: jiff::Timestamp,
}

/// Toasty model for `yauth_revocations`.
#[derive(Debug, toasty::Model)]
#[table = "revocations"]
pub struct YauthRevocation {
    #[key]
    pub key: String,
    pub expires_at: jiff::Timestamp,
}

/// Toasty model for `yauth_oauth_states`.
#[derive(Debug, toasty::Model)]
#[table = "oauth_states"]
pub struct YauthOauthState {
    #[key]
    pub state: String,
    pub provider: String,
    pub redirect_url: Option<String>,
    pub expires_at: jiff::Timestamp,
    pub created_at: jiff::Timestamp,
}

/// Toasty model for `yauth_magic_links`.
#[derive(Debug, toasty::Model)]
#[table = "magic_links"]
pub struct YauthMagicLink {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    pub email: String,
    #[unique]
    pub token_hash: String,
    pub expires_at: jiff::Timestamp,
    pub used: bool,
    pub created_at: jiff::Timestamp,
}

/// Toasty model for `yauth_oauth2_clients`.
#[derive(Debug, toasty::Model)]
#[table = "oauth2_clients"]
pub struct YauthOauth2Client {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[unique]
    pub client_id: String,
    pub client_secret_hash: Option<String>,
    #[serialize(json)]
    pub redirect_uris: serde_json::Value,
    pub client_name: Option<String>,
    #[serialize(json)]
    pub grant_types: serde_json::Value,
    #[serialize(json)]
    pub scopes: Option<serde_json::Value>,
    pub is_public: bool,
    pub created_at: jiff::Timestamp,
    pub token_endpoint_auth_method: Option<String>,
    pub public_key_pem: Option<String>,
    pub jwks_uri: Option<String>,
    pub banned_at: Option<jiff::Timestamp>,
    pub banned_reason: Option<String>,
}

/// Toasty model for `yauth_webhooks`.
#[derive(Debug, toasty::Model)]
#[table = "webhooks"]
pub struct YauthWebhook {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    pub url: String,
    pub secret: String,
    #[serialize(json)]
    pub events: serde_json::Value,
    pub active: bool,
    pub created_at: jiff::Timestamp,
    pub updated_at: jiff::Timestamp,
    #[has_many]
    pub webhook_deliveries: toasty::HasMany<YauthWebhookDelivery>,
}

/// Toasty model for `yauth_oidc_nonces`.
#[derive(Debug, toasty::Model)]
#[table = "oidc_nonces"]
pub struct YauthOidcNonce {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[unique]
    pub nonce_hash: String,
    pub authorization_code_id: uuid::Uuid,
    pub created_at: jiff::Timestamp,
}

/// Toasty model for `yauth_sessions`.
#[derive(Debug, toasty::Model)]
#[table = "sessions"]
pub struct YauthSession {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    pub user_id: uuid::Uuid,
    #[belongs_to(key = user_id, references = id)]
    pub yauth_user: toasty::BelongsTo<YauthUser>,
    #[unique]
    pub token_hash: String,
    pub ip_address: Option<String>,
    pub user_agent: Option<String>,
    pub expires_at: jiff::Timestamp,
    pub created_at: jiff::Timestamp,
}

/// Toasty model for `yauth_audit_log`.
#[derive(Debug, toasty::Model)]
#[table = "audit_log"]
pub struct YauthAuditLog {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    pub user_id: Option<uuid::Uuid>,
    #[belongs_to(key = user_id, references = id)]
    pub yauth_user: toasty::BelongsTo<YauthUser>,
    pub event_type: String,
    #[serialize(json)]
    pub metadata: Option<serde_json::Value>,
    pub ip_address: Option<String>,
    pub created_at: jiff::Timestamp,
}

/// Toasty model for `yauth_passwords`.
#[derive(Debug, toasty::Model)]
#[table = "passwords"]
pub struct YauthPassword {
    #[key]
    #[auto]
    pub user_id: uuid::Uuid,
    #[belongs_to(key = user_id, references = id)]
    pub yauth_user: toasty::BelongsTo<YauthUser>,
    pub password_hash: String,
}

/// Toasty model for `yauth_email_verifications`.
#[derive(Debug, toasty::Model)]
#[table = "email_verifications"]
pub struct YauthEmailVerification {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    pub user_id: Option<uuid::Uuid>,
    #[belongs_to(key = user_id, references = id)]
    pub yauth_user: toasty::BelongsTo<YauthUser>,
    #[unique]
    pub token_hash: String,
    pub expires_at: jiff::Timestamp,
    pub created_at: jiff::Timestamp,
}

/// Toasty model for `yauth_password_resets`.
#[derive(Debug, toasty::Model)]
#[table = "password_resets"]
pub struct YauthPasswordReset {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    pub user_id: Option<uuid::Uuid>,
    #[belongs_to(key = user_id, references = id)]
    pub yauth_user: toasty::BelongsTo<YauthUser>,
    #[unique]
    pub token_hash: String,
    pub expires_at: jiff::Timestamp,
    pub used_at: Option<jiff::Timestamp>,
    pub created_at: jiff::Timestamp,
}

/// Toasty model for `yauth_webauthn_credentials`.
#[derive(Debug, toasty::Model)]
#[table = "webauthn_credentials"]
pub struct YauthWebauthnCredential {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    pub user_id: Option<uuid::Uuid>,
    #[belongs_to(key = user_id, references = id)]
    pub yauth_user: toasty::BelongsTo<YauthUser>,
    pub name: String,
    pub aaguid: Option<String>,
    pub device_name: Option<String>,
    #[serialize(json)]
    pub credential: serde_json::Value,
    pub created_at: jiff::Timestamp,
    pub last_used_at: Option<jiff::Timestamp>,
}

/// Toasty model for `yauth_totp_secrets`.
#[derive(Debug, toasty::Model)]
#[table = "totp_secrets"]
pub struct YauthTotpSecret {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[unique]
    pub user_id: Option<uuid::Uuid>,
    #[belongs_to(key = user_id, references = id)]
    pub yauth_user: toasty::BelongsTo<YauthUser>,
    pub encrypted_secret: String,
    pub verified: bool,
    pub created_at: jiff::Timestamp,
}

/// Toasty model for `yauth_backup_codes`.
#[derive(Debug, toasty::Model)]
#[table = "backup_codes"]
pub struct YauthBackupCode {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    pub user_id: Option<uuid::Uuid>,
    #[belongs_to(key = user_id, references = id)]
    pub yauth_user: toasty::BelongsTo<YauthUser>,
    pub code_hash: String,
    pub used: bool,
    pub created_at: jiff::Timestamp,
}

/// Toasty model for `yauth_oauth_accounts`.
#[derive(Debug, toasty::Model)]
#[table = "oauth_accounts"]
pub struct YauthOauthAccount {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    pub user_id: Option<uuid::Uuid>,
    #[belongs_to(key = user_id, references = id)]
    pub yauth_user: toasty::BelongsTo<YauthUser>,
    pub provider: String,
    pub provider_user_id: String,
    pub access_token_enc: Option<String>,
    pub refresh_token_enc: Option<String>,
    pub created_at: jiff::Timestamp,
    pub expires_at: Option<jiff::Timestamp>,
    pub updated_at: jiff::Timestamp,
}

/// Toasty model for `yauth_refresh_tokens`.
#[derive(Debug, toasty::Model)]
#[table = "refresh_tokens"]
pub struct YauthRefreshToken {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    pub user_id: Option<uuid::Uuid>,
    #[belongs_to(key = user_id, references = id)]
    pub yauth_user: toasty::BelongsTo<YauthUser>,
    #[unique]
    pub token_hash: String,
    pub family_id: uuid::Uuid,
    pub expires_at: jiff::Timestamp,
    pub revoked: bool,
    pub created_at: jiff::Timestamp,
}

/// Toasty model for `yauth_api_keys`.
#[derive(Debug, toasty::Model)]
#[table = "api_keys"]
pub struct YauthApiKey {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    pub user_id: Option<uuid::Uuid>,
    #[belongs_to(key = user_id, references = id)]
    pub yauth_user: toasty::BelongsTo<YauthUser>,
    #[unique]
    pub key_prefix: String,
    pub key_hash: String,
    pub name: String,
    #[serialize(json)]
    pub scopes: Option<serde_json::Value>,
    pub last_used_at: Option<jiff::Timestamp>,
    pub expires_at: Option<jiff::Timestamp>,
    pub created_at: jiff::Timestamp,
}

/// Toasty model for `yauth_authorization_codes`.
#[derive(Debug, toasty::Model)]
#[table = "authorization_codes"]
pub struct YauthAuthorizationCode {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[unique]
    pub code_hash: String,
    pub client_id: String,
    pub user_id: Option<uuid::Uuid>,
    #[belongs_to(key = user_id, references = id)]
    pub yauth_user: toasty::BelongsTo<YauthUser>,
    #[serialize(json)]
    pub scopes: Option<serde_json::Value>,
    pub redirect_uri: String,
    pub code_challenge: String,
    pub code_challenge_method: String,
    pub expires_at: jiff::Timestamp,
    pub used: bool,
    pub nonce: Option<String>,
    pub created_at: jiff::Timestamp,
}

/// Toasty model for `yauth_consents`.
#[derive(Debug, toasty::Model)]
#[table = "consents"]
pub struct YauthConsent {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    pub user_id: Option<uuid::Uuid>,
    #[belongs_to(key = user_id, references = id)]
    pub yauth_user: toasty::BelongsTo<YauthUser>,
    pub client_id: String,
    #[serialize(json)]
    pub scopes: Option<serde_json::Value>,
    pub created_at: jiff::Timestamp,
}

/// Toasty model for `yauth_device_codes`.
#[derive(Debug, toasty::Model)]
#[table = "device_codes"]
pub struct YauthDeviceCode {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[unique]
    pub device_code_hash: String,
    #[unique]
    pub user_code: String,
    pub client_id: String,
    #[serialize(json)]
    pub scopes: Option<serde_json::Value>,
    pub user_id: Option<uuid::Uuid>,
    #[belongs_to(key = user_id, references = id)]
    pub yauth_user: toasty::BelongsTo<YauthUser>,
    pub status: String,
    pub interval: i64,
    pub expires_at: jiff::Timestamp,
    pub last_polled_at: Option<jiff::Timestamp>,
    pub created_at: jiff::Timestamp,
}

/// Toasty model for `yauth_account_locks`.
#[derive(Debug, toasty::Model)]
#[table = "account_locks"]
pub struct YauthAccountLock {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    #[unique]
    pub user_id: Option<uuid::Uuid>,
    #[belongs_to(key = user_id, references = id)]
    pub yauth_user: toasty::BelongsTo<YauthUser>,
    pub failed_count: i64,
    pub locked_until: Option<jiff::Timestamp>,
    pub lock_count: i64,
    pub locked_reason: Option<String>,
    pub created_at: jiff::Timestamp,
    pub updated_at: jiff::Timestamp,
}

/// Toasty model for `yauth_unlock_tokens`.
#[derive(Debug, toasty::Model)]
#[table = "unlock_tokens"]
pub struct YauthUnlockToken {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    pub user_id: Option<uuid::Uuid>,
    #[belongs_to(key = user_id, references = id)]
    pub yauth_user: toasty::BelongsTo<YauthUser>,
    #[unique]
    pub token_hash: String,
    pub expires_at: jiff::Timestamp,
    pub created_at: jiff::Timestamp,
}

/// Toasty model for `yauth_webhook_deliveries`.
#[derive(Debug, toasty::Model)]
#[table = "webhook_deliveries"]
pub struct YauthWebhookDelivery {
    #[key]
    #[auto]
    pub id: uuid::Uuid,
    pub webhook_id: Option<uuid::Uuid>,
    #[belongs_to(key = webhook_id, references = id)]
    pub yauth_webhook: toasty::BelongsTo<YauthWebhook>,
    pub event_type: String,
    #[serialize(json)]
    pub payload: serde_json::Value,
    pub status_code: Option<i64>,
    pub response_body: Option<String>,
    pub success: bool,
    pub attempt: i64,
    pub created_at: jiff::Timestamp,
}
