<script setup lang="ts">
import { useRouter } from "vue-router";
import { useQueryClient } from "@tanstack/vue-query";
// Generated by orval from the merged OpenAPI spec.
// useGetSession is a query (GET), useLogout is a mutation (POST).
import { useGetSession, useLogout } from "../generated";

const router = useRouter();
const queryClient = useQueryClient();

// TanStack Query handles loading, error, and caching automatically.
// The session is refetched on window focus by default.
const { data: user, isLoading, isError } = useGetSession();

const logout = useLogout({
	mutation: {
		onSuccess: () => {
			queryClient.invalidateQueries({ queryKey: ["getSession"] });
			router.push("/login");
		},
	},
});
</script>

<template>
  <h1>Dashboard</h1>
  <div v-if="isLoading">Loading...</div>
  <div v-else-if="isError || !user">
    <p>Not logged in.</p>
    <RouterLink to="/login">Go to login</RouterLink>
  </div>
  <div v-else>
    <p>Logged in as <strong>{{ user.email }}</strong></p>
    <p style="margin-top: 8px; color: #666; font-size: 14px;">
      Role: {{ user.role }} |
      Email verified: {{ user.email_verified ? "Yes" : "No" }}
    </p>
    <button style="margin-top: 16px;" :disabled="logout.isPending.value"
      @click="logout.mutate()">
      {{ logout.isPending.value ? "Logging out..." : "Logout" }}
    </button>
  </div>
</template>
