<script setup lang="ts">
import { ref } from "vue";
import { useRouter } from "vue-router";
import { useQueryClient } from "@tanstack/vue-query";
// These hooks are generated by orval from the merged OpenAPI spec.
// In a real app, run `bun generate` to produce this file.
import { useEmailPasswordLogin, useMfaVerify } from "../generated";

const router = useRouter();
const queryClient = useQueryClient();

const email = ref("");
const password = ref("");
const mfaPending = ref<string | null>(null);
const mfaCode = ref("");
const error = ref<string | null>(null);

const login = useEmailPasswordLogin({
	mutation: {
		onSuccess: (data: any) => {
			if (data?.mfa_required) {
				mfaPending.value = data.pending_session_id;
			} else {
				// Invalidate session query so dashboard refetches
				queryClient.invalidateQueries({ queryKey: ["getSession"] });
				router.push("/dashboard");
			}
		},
		onError: (err: Error) => {
			error.value = err.message;
		},
	},
});

const verifyMfa = useMfaVerify({
	mutation: {
		onSuccess: () => {
			queryClient.invalidateQueries({ queryKey: ["getSession"] });
			router.push("/dashboard");
		},
		onError: (err: Error) => {
			error.value = err.message;
		},
	},
});

const handleLogin = () => {
	error.value = null;
	login.mutate({ data: { email: email.value, password: password.value } });
};

const handleMfa = () => {
	error.value = null;
	verifyMfa.mutate({
		data: { code: mfaCode.value, pending_session_id: mfaPending.value! },
	});
};
</script>

<template>
  <h1>Login</h1>

  <!-- MFA challenge -->
  <form v-if="mfaPending" @submit.prevent="handleMfa">
    <p style="margin-bottom: 12px; color: #666;">
      Enter the code from your authenticator app.
    </p>
    <input v-model="mfaCode" type="text" inputmode="numeric" maxlength="6"
      placeholder="000000" required />
    <p v-if="error" style="color: red; margin-top: 8px;">{{ error }}</p>
    <button type="submit" :disabled="verifyMfa.isPending.value">
      {{ verifyMfa.isPending.value ? "Verifying..." : "Verify" }}
    </button>
  </form>

  <!-- Normal login -->
  <form v-else @submit.prevent="handleLogin">
    <input v-model="email" type="email" placeholder="Email" required />
    <input v-model="password" type="password" placeholder="Password" required />
    <p v-if="error" style="color: red; margin-top: 8px;">{{ error }}</p>
    <button type="submit" :disabled="login.isPending.value">
      {{ login.isPending.value ? "Signing in..." : "Sign in" }}
    </button>
  </form>

  <p style="margin-top: 12px; font-size: 14px;">
    Don't have an account? <RouterLink to="/register">Register</RouterLink>
  </p>
</template>
