<script setup lang="ts">
import { ref } from "vue";
import { useRouter } from "vue-router";
// Generated by orval from the merged OpenAPI spec.
import { useEmailPasswordRegister } from "../generated";

const router = useRouter();
const email = ref("");
const password = ref("");
const successMessage = ref<string | null>(null);

const register = useEmailPasswordRegister({
	mutation: {
		onSuccess: (data) => {
			const result = data as Record<string, string> | undefined;
			successMessage.value =
				result?.message || "Registration successful! Please log in.";
			setTimeout(() => router.push("/login"), 2000);
		},
	},
});

const handleRegister = () => {
	register.mutate({ data: { email: email.value, password: password.value } });
};
</script>

<template>
  <h1>Register</h1>
  <div v-if="successMessage" style="color: green;">{{ successMessage }}</div>
  <form v-else @submit.prevent="handleRegister">
    <input v-model="email" type="email" placeholder="Email" required />
    <input v-model="password" type="password" placeholder="Password" required />
    <p v-if="register.error.value" style="color: red; margin-top: 8px;">
      {{ (register.error.value as Error)?.message }}
    </p>
    <button type="submit" :disabled="register.isPending.value">
      {{ register.isPending.value ? "Creating account..." : "Register" }}
    </button>
  </form>
  <p style="margin-top: 12px; font-size: 14px;">
    Already have an account? <RouterLink to="/login">Login</RouterLink>
  </p>
</template>
