// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User info returned by admin list endpoint.
 */
export type AdminUserInfo = { id: string, email: string, display_name: string | null, email_verified: boolean, role: string, banned: boolean, banned_reason: string | null, banned_until: string | null, created_at: string, updated_at: string, };
