// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateApiKeyRequest = {
	name: string;
	scopes: Array<string> | null;
	expires_in_days: number | null;
};
