// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoginRequest = { email: string, password: string, 
/**
 * When true and `remember_me_ttl` is configured, uses a longer session TTL.
 */
remember_me: boolean | null, };
