// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OAuthAccountResponse = { id: string, provider: string, provider_user_id: string, created_at: string, };
