// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminUserInfo } from "./AdminUserInfo";

/**
 * Response type for `GET /admin/users` (schema-only, used for OpenAPI spec).
 */
export type PaginatedUsersResponse = { users: Array<AdminUserInfo>, total: bigint, page: bigint, per_page: bigint, };
