// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PasskeyInfo = {
	id: string;
	name: string;
	created_at: string;
	last_used_at: string | null;
};
