// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TokenResponse = {
	access_token: string;
	refresh_token: string;
	token_type: string;
	expires_in: bigint;
};
