// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateUserRequest = { display_name: string | null, role: string | null, email_verified: boolean | null, };
