// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateWebhookRequest = { url: string | null, events: Array<string> | null, secret: string | null, active: boolean | null, };
