// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebhookResponse = { id: string, url: string, events: Array<string>, active: boolean, created_at: string, updated_at: string, };
