// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WebhookDeliveryResponse } from "./WebhookDeliveryResponse";
import type { WebhookResponse } from "./WebhookResponse";

export type WebhookDetailResponse = { webhook: WebhookResponse, recent_deliveries: Array<WebhookDeliveryResponse>, };
