-- Generated by cargo-yauth
-- Registered user accounts.
CREATE TABLE IF NOT EXISTS yauth_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR NOT NULL UNIQUE,
    display_name VARCHAR,
    email_verified BOOLEAN NOT NULL DEFAULT false,
    role VARCHAR NOT NULL DEFAULT 'user',
    banned BOOLEAN NOT NULL DEFAULT false,
    banned_reason VARCHAR,
    banned_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Ephemeral challenge storage for CSRF, WebAuthn, and MFA flows.
CREATE TABLE IF NOT EXISTS yauth_challenges (
    key VARCHAR(255) PRIMARY KEY,
    value JSONB NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL
);

-- Per-operation rate limit counters.
CREATE TABLE IF NOT EXISTS yauth_rate_limits (
    key VARCHAR(255) PRIMARY KEY,
    count INT NOT NULL DEFAULT 1,
    window_start TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Revoked JWT token IDs (JTI). TTL-based expiration.
CREATE TABLE IF NOT EXISTS yauth_revocations (
    key VARCHAR(255) PRIMARY KEY,
    expires_at TIMESTAMPTZ NOT NULL
);

-- OAuth CSRF state tokens. Consumed on callback.
CREATE TABLE IF NOT EXISTS yauth_oauth_states (
    state VARCHAR PRIMARY KEY,
    provider VARCHAR NOT NULL,
    redirect_url VARCHAR,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Passwordless login tokens. Single-use, time-limited.
CREATE TABLE IF NOT EXISTS yauth_magic_links (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR NOT NULL,
    token_hash VARCHAR NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Registered OAuth2 server clients.
CREATE TABLE IF NOT EXISTS yauth_oauth2_clients (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id VARCHAR NOT NULL UNIQUE,
    client_secret_hash VARCHAR,
    redirect_uris JSONB NOT NULL,
    client_name VARCHAR,
    grant_types JSONB NOT NULL,
    scopes JSONB,
    is_public BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    token_endpoint_auth_method VARCHAR,
    public_key_pem TEXT,
    jwks_uri VARCHAR,
    banned_at TIMESTAMPTZ,
    banned_reason VARCHAR
);

-- Webhook endpoint configurations.
CREATE TABLE IF NOT EXISTS yauth_webhooks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    url VARCHAR NOT NULL,
    secret VARCHAR NOT NULL,
    events JSONB NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- OIDC nonce values for replay protection.
CREATE TABLE IF NOT EXISTS yauth_oidc_nonces (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nonce_hash VARCHAR NOT NULL UNIQUE,
    authorization_code_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Active user sessions. One row per login.
CREATE TABLE IF NOT EXISTS yauth_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES yauth_users(id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    ip_address VARCHAR,
    user_agent VARCHAR,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Append-only authentication event log.
CREATE TABLE IF NOT EXISTS yauth_audit_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES yauth_users(id) ON DELETE SET NULL,
    event_type VARCHAR NOT NULL,
    metadata JSONB,
    ip_address VARCHAR,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Hashed passwords. One row per user.
CREATE TABLE IF NOT EXISTS yauth_passwords (
    user_id UUID PRIMARY KEY REFERENCES yauth_users(id) ON DELETE CASCADE,
    password_hash VARCHAR NOT NULL
);

-- Pending email verification tokens.
CREATE TABLE IF NOT EXISTS yauth_email_verifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES yauth_users(id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Pending password reset tokens.
CREATE TABLE IF NOT EXISTS yauth_password_resets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES yauth_users(id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- WebAuthn/passkey credentials. Multiple per user.
CREATE TABLE IF NOT EXISTS yauth_webauthn_credentials (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES yauth_users(id) ON DELETE CASCADE,
    name VARCHAR NOT NULL,
    aaguid VARCHAR,
    device_name VARCHAR,
    credential JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_used_at TIMESTAMPTZ
);

-- TOTP secrets for MFA. One per user.
CREATE TABLE IF NOT EXISTS yauth_totp_secrets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES yauth_users(id) ON DELETE CASCADE UNIQUE,
    encrypted_secret VARCHAR NOT NULL,
    verified BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- MFA backup codes. Multiple per user, single-use.
CREATE TABLE IF NOT EXISTS yauth_backup_codes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES yauth_users(id) ON DELETE CASCADE,
    code_hash VARCHAR(64) NOT NULL,
    used BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Linked OAuth provider accounts.
CREATE TABLE IF NOT EXISTS yauth_oauth_accounts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES yauth_users(id) ON DELETE CASCADE,
    provider VARCHAR NOT NULL,
    provider_user_id VARCHAR NOT NULL,
    access_token_enc VARCHAR,
    refresh_token_enc VARCHAR,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- JWT refresh tokens with rotation family tracking.
CREATE TABLE IF NOT EXISTS yauth_refresh_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES yauth_users(id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    family_id UUID NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- API keys. Identified by prefix, verified by hash.
CREATE TABLE IF NOT EXISTS yauth_api_keys (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES yauth_users(id) ON DELETE CASCADE,
    key_prefix VARCHAR(12) NOT NULL UNIQUE,
    key_hash VARCHAR(64) NOT NULL,
    name VARCHAR NOT NULL,
    scopes JSONB,
    last_used_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- OAuth2 authorization codes. Single-use, time-limited.
CREATE TABLE IF NOT EXISTS yauth_authorization_codes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code_hash VARCHAR NOT NULL UNIQUE,
    client_id VARCHAR NOT NULL,
    user_id UUID REFERENCES yauth_users(id) ON DELETE CASCADE,
    scopes JSONB,
    redirect_uri VARCHAR NOT NULL,
    code_challenge VARCHAR NOT NULL,
    code_challenge_method VARCHAR NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used BOOLEAN NOT NULL DEFAULT false,
    nonce VARCHAR,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- User consent records for OAuth2 clients.
CREATE TABLE IF NOT EXISTS yauth_consents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES yauth_users(id) ON DELETE CASCADE,
    client_id VARCHAR NOT NULL,
    scopes JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Device authorization flow codes.
CREATE TABLE IF NOT EXISTS yauth_device_codes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_code_hash VARCHAR NOT NULL UNIQUE,
    user_code VARCHAR NOT NULL UNIQUE,
    client_id VARCHAR NOT NULL,
    scopes JSONB,
    user_id UUID REFERENCES yauth_users(id) ON DELETE CASCADE,
    status VARCHAR NOT NULL DEFAULT 'pending',
    interval INT NOT NULL DEFAULT 5,
    expires_at TIMESTAMPTZ NOT NULL,
    last_polled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Account lockout state. One row per user.
CREATE TABLE IF NOT EXISTS yauth_account_locks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES yauth_users(id) ON DELETE CASCADE UNIQUE,
    failed_count INT NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ,
    lock_count INT NOT NULL DEFAULT 0,
    locked_reason VARCHAR,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Account unlock tokens. Time-limited.
CREATE TABLE IF NOT EXISTS yauth_unlock_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES yauth_users(id) ON DELETE CASCADE,
    token_hash VARCHAR NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Webhook delivery attempts and responses.
CREATE TABLE IF NOT EXISTS yauth_webhook_deliveries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    webhook_id UUID REFERENCES yauth_webhooks(id) ON DELETE CASCADE,
    event_type VARCHAR NOT NULL,
    payload JSONB NOT NULL,
    status_code SMALLINT,
    response_body TEXT,
    success BOOLEAN NOT NULL DEFAULT false,
    attempt INT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

